#pragma once
#include "../../../Common/AbstractSingleton.hpp"
#include "../../../Common/BasicCrypt.hpp"
#include "../../../Common/StdExtended.hpp"
#include "../../../Common/HandleGuard.hpp"
#include <phnt_windows.h>
#include <phnt.h>
#include "WinTypes.hpp"
#include "NtAPIWrapper.hpp"
#include "SyscallHelper.hpp"
#include "SecureLoadLibrary.hpp"
#include "../../EngineR3/SelfProtection/Pointers.hpp"

#undef DnsRecordListFree
#ifdef _WIN64
#undef SymGetSymFromAddr
#endif

namespace NoMercyCore
{
	enum class EModuleIntegrityRet : uint8_t
	{
		NONE,
		NAME_QUERY_FAIL,
		READ_FAIL,
		MALFORMED_PATH,
		SXS_REDIRECT_FAIL,
		SFC_FAIL,
		CHECKSUM_MAPPED_FAIL,
		MODULE_PE_NOT_VALID,
		FILE_PE_NOT_VALID,
		MODULE_HIJACKED,
		IAT_HOOKS,
		EAT_HOOKS,
		FILE_NOT_SIGNED,
		FILE_CERT_NOT_VALID,
		UNALLOWED_LOAD_REASON,
		UNALLOWED_LOAD_REASON_DYN,
		VERSION_INFO_QUERY_FAIL,
		INVALID_COMPANY_NAME
	};

	struct STextSectionCtx
	{
		LPVOID lpBase{ nullptr };
		std::size_t cbSize{ 0 };
	};

	struct SWinModuleTable
	{
		// Common system modules
		HMODULE hAdvapi32{ nullptr };
		HMODULE hBaseModule{ nullptr };
		HMODULE hCrypt32{ nullptr };
		HMODULE hDbghelp{ nullptr };
		HMODULE hDnsapi{ nullptr };
		HMODULE hFltlib{ nullptr };
		HMODULE hGdi32{ nullptr };
		HMODULE hImagehlp{ nullptr };
		HMODULE hImm32{ nullptr };
		HMODULE hInetmib1{ nullptr };
		HMODULE hIphlpapi{ nullptr };
		HMODULE hKernel32{ nullptr };
		HMODULE hKernelbase{ nullptr };
		HMODULE hMpr{ nullptr };
		HMODULE hMsCoree{ nullptr };
		HMODULE hMsimg32{ nullptr };
		HMODULE hNetapi32{ nullptr };
		HMODULE hNtdll{ nullptr };
		HMODULE hOle32{ nullptr };
		HMODULE hOleAut32{ nullptr };
		HMODULE hPsapi{ nullptr };
		HMODULE hSetupapi{ nullptr };
		HMODULE hSfc{ nullptr };
		HMODULE hShell32{ nullptr };
		HMODULE hShlwapi{ nullptr };
		HMODULE hSnmpapi{ nullptr };
		HMODULE hSrclient{ nullptr };
		HMODULE hTBS{ nullptr };
		HMODULE hTDH{ nullptr };
		HMODULE hUser32{ nullptr };
		HMODULE hUserEnv{ nullptr };
		HMODULE hVersion{ nullptr };
		HMODULE hWevtapi{ nullptr };
		HMODULE hWin32u{ nullptr };
		HMODULE hWindowsCodecs{ nullptr };
		HMODULE hWininet{ nullptr };
		HMODULE hWinmm{ nullptr };
		HMODULE hWinsta{ nullptr };
		HMODULE hWintrust{ nullptr };
		HMODULE hWs2_32{ nullptr };
		HMODULE hWtsapi32{ nullptr };
		HMODULE hSlwga{ nullptr };
		HMODULE hRpcrt4{ nullptr };
		HMODULE hMsi{ nullptr };
		HMODULE hPowrProf{ nullptr };
		HMODULE hMsvcrt{ nullptr };
		HMODULE hBCD{ nullptr };
		HMODULE hUcrtbase{ nullptr };
		HMODULE hW32time{ nullptr };
		HMODULE hUxtheme{ nullptr };
		HMODULE hDwmapi{ nullptr };
		HMODULE hGdiplus{ nullptr };

		// Original / Non-modified shadow copies
		HMODULE hNtdll_o{ nullptr };

		// Game specific modules
		HMODULE hPython{ nullptr };

	};

	struct SWinAPITable
	{
		// Proxy routines
		decltype(&GetModuleHandleW) GetModuleHandleW{ nullptr };
		decltype(&GetProcAddress) GetProcAddress{ nullptr };
		// Original copies of proxy routines
		decltype(&::GetModuleHandleW) GetModuleHandleW_o{ nullptr };
		decltype(&::GetProcAddress) GetProcAddress_o{ nullptr };
		// Standart WinAPI calls
		decltype(&AccessCheck) AccessCheck{ nullptr };
		decltype(&AddAccessAllowedAce) AddAccessAllowedAce{ nullptr };
		decltype(&AddAccessDeniedAce) AddAccessDeniedAce{ nullptr };
		decltype(&AddVectoredContinueHandler) AddVectoredContinueHandler{ nullptr };
		decltype(&AddVectoredExceptionHandler) AddVectoredExceptionHandler{ nullptr };
		decltype(&AdjustTokenPrivileges) AdjustTokenPrivileges{ nullptr };
		decltype(&AdjustWindowRect) AdjustWindowRect{ nullptr };
		decltype(&AllocConsole) AllocConsole{ nullptr };
		decltype(&AllocateAndInitializeSid) AllocateAndInitializeSid{ nullptr };
		decltype(&AllocateUserPhysicalPages) AllocateUserPhysicalPages{ nullptr };
		decltype(&AlphaBlend) AlphaBlend{ nullptr };
		decltype(&AnimateWindow) AnimateWindow{ nullptr };
		decltype(&AppendMenuW) AppendMenuW{ nullptr };
		decltype(&AssignProcessToJobObject) AssignProcessToJobObject{ nullptr };
		decltype(&BcdCloseObject) BcdCloseObject{ nullptr };
		decltype(&BcdCloseStore) BcdCloseStore{ nullptr };
		decltype(&BcdEnumerateAndUnpackElements) BcdEnumerateAndUnpackElements{ nullptr };
		decltype(&BcdEnumerateObjects) BcdEnumerateObjects{ nullptr };
		decltype(&BcdGetElementData) BcdGetElementData{ nullptr };
		decltype(&BcdOpenObject) BcdOpenObject{ nullptr };
		decltype(&BcdOpenSystemStore) BcdOpenSystemStore{ nullptr };
		decltype(&BcdSetElementData) BcdSetElementData{ nullptr };
		decltype(&BcdSetLogging) BcdSetLogging{ nullptr };
		decltype(&BeginPaint) BeginPaint{ nullptr };
		decltype(&BitBlt) BitBlt{ nullptr };
		decltype(&BlockInput) BlockInput{ nullptr };
		decltype(&BuildExplicitAccessWithNameW) BuildExplicitAccessWithNameW{ nullptr };
		decltype(&CLSIDFromString) CLSIDFromString{ nullptr };
		decltype(&CallNamedPipeW) CallNamedPipeW{ nullptr };
		decltype(&CallNextHookEx) CallNextHookEx{ nullptr };
		decltype(&CallNtPowerInformation) CallNtPowerInformation{ nullptr };
		decltype(&CallWindowProcA) CallWindowProcA{ nullptr };
		decltype(&CallWindowProcW) CallWindowProcW{ nullptr };
		decltype(&CancelThreadpoolIo) CancelThreadpoolIo{ nullptr };
		decltype(&CertCloseStore) CertCloseStore{ nullptr };
		decltype(&CertCompareCertificateName) CertCompareCertificateName{ nullptr };
		decltype(&CertEnumCertificatesInStore) CertEnumCertificatesInStore{ nullptr };
		decltype(&CertEnumSystemStore) CertEnumSystemStore{ nullptr };
		decltype(&CertEnumSystemStoreLocation) CertEnumSystemStoreLocation{ nullptr };
		decltype(&CertFindCertificateInStore) CertFindCertificateInStore{ nullptr };
		decltype(&CertFindExtension) CertFindExtension{ nullptr };
		decltype(&CertFreeCertificateChain) CertFreeCertificateChain{ nullptr };
		decltype(&CertFreeCertificateContext) CertFreeCertificateContext{ nullptr };
		decltype(&CertGetCertificateChain) CertGetCertificateChain{ nullptr };
		decltype(&CertGetNameStringW) CertGetNameStringW{ nullptr };
		decltype(&CertGetSubjectCertificateFromStore) CertGetSubjectCertificateFromStore{ nullptr };
		decltype(&CertNameToStrW) CertNameToStrW{ nullptr };
		decltype(&CertOpenStore) CertOpenStore{ nullptr };
		decltype(&CertVerifyCertificateChainPolicy) CertVerifyCertificateChainPolicy{ nullptr };
		decltype(&CertVerifySubjectCertificateContext) CertVerifySubjectCertificateContext{ nullptr };
		decltype(&CertVerifyRevocation) CertVerifyRevocation{ nullptr };
		decltype(&CertVerifyTimeValidity) CertVerifyTimeValidity{ nullptr };
		decltype(&ChangeServiceConfig2W) ChangeServiceConfig2W{ nullptr };
		decltype(&CharUpperBuffW) CharUpperBuffW{ nullptr };
		decltype(&CheckRemoteDebuggerPresent) CheckRemoteDebuggerPresent{ nullptr };
		decltype(&CheckTokenMembership) CheckTokenMembership{ nullptr };
		decltype(&ClientToScreen) ClientToScreen{ nullptr };
		decltype(&CloseClipboard) CloseClipboard{ nullptr };
		decltype(&CloseDesktop) CloseDesktop{ nullptr };
		decltype(&CloseHandle) CloseHandle{ nullptr };
		decltype(&CloseServiceHandle) CloseServiceHandle{ nullptr };
		decltype(&CloseThreadpool) CloseThreadpool{ nullptr };
		decltype(&CloseThreadpoolIo) CloseThreadpoolIo{ nullptr };
		decltype(&CloseThreadpoolTimer) CloseThreadpoolTimer{ nullptr };
		decltype(&CloseThreadpoolWait) CloseThreadpoolWait{ nullptr };
		decltype(&CloseThreadpoolWork) CloseThreadpoolWork{ nullptr };
		decltype(&CloseWindow) CloseWindow{ nullptr };
		decltype(&CloseWindowStation) CloseWindowStation{ nullptr };
		decltype(&CoCreateInstance) CoCreateInstance{ nullptr };
		decltype(&CoInitialize) CoInitialize{ nullptr };
		decltype(&CoInitializeEx) CoInitializeEx{ nullptr };
		decltype(&CoInitializeSecurity) CoInitializeSecurity{ nullptr };
		decltype(&CoSetProxyBlanket) CoSetProxyBlanket{ nullptr };
		decltype(&CoTaskMemFree) CoTaskMemFree{ nullptr };
		decltype(&CoUninitialize) CoUninitialize{ nullptr };
		decltype(&CommandLineToArgvW) CommandLineToArgvW{ nullptr };
		decltype(&ConnectNamedPipe) ConnectNamedPipe{ nullptr };
		decltype(&ControlService) ControlService{ nullptr };
		decltype(&ControlServiceExW) ControlServiceExW{ nullptr };
		decltype(&ControlTraceW) ControlTraceW{ nullptr };
		decltype(&ConvertSidToStringSidW) ConvertSidToStringSidW{ nullptr };
		decltype(&ConvertStringSecurityDescriptorToSecurityDescriptorW) ConvertStringSecurityDescriptorToSecurityDescriptorW{ nullptr };
		decltype(&CopyFileW) CopyFileW{ nullptr };
		decltype(&CopyRect) CopyRect{ nullptr };
		decltype(&CorExitProcess) CorExitProcess{ nullptr };
		decltype(&CreateBitmap) CreateBitmap{ nullptr };
		decltype(&CreateCompatibleBitmap) CreateCompatibleBitmap{ nullptr };
		decltype(&CreateCompatibleDC) CreateCompatibleDC{ nullptr };
		decltype(&CreateDIBSection) CreateDIBSection{ nullptr };
		decltype(&CreateDirectoryW) CreateDirectoryW{ nullptr };
		decltype(&CreateEventW) CreateEventW{ nullptr };
		decltype(&CreateFileW) CreateFileW{ nullptr };
		decltype(&CreateFileMappingW) CreateFileMappingW{ nullptr };
		decltype(&CreateFontW) CreateFontW{ nullptr };
		decltype(&CreateFontIndirectW) CreateFontIndirectW{ nullptr };
		decltype(&CreateJobObjectW) CreateJobObjectW{ nullptr };
		decltype(&CreateMailslotW) CreateMailslotW{ nullptr };
		decltype(&CreateMutexW) CreateMutexW{ nullptr };
		decltype(&CreateNamedPipeW) CreateNamedPipeW{ nullptr };
		decltype(&CreatePen) CreatePen{ nullptr };
		decltype(&CreatePipe) CreatePipe{ nullptr };
		decltype(&CreatePopupMenu) CreatePopupMenu{ nullptr };
		decltype(&CreateProcessW) CreateProcessW{ nullptr };
		decltype(&CreateProcessAsUserW) CreateProcessAsUserW{ nullptr };
		decltype(&CreateRemoteThread) CreateRemoteThread{ nullptr };
		decltype(&CreateServiceW) CreateServiceW{ nullptr };
		decltype(&CreateSolidBrush) CreateSolidBrush{ nullptr };
		decltype(&CreateStreamOnHGlobal) CreateStreamOnHGlobal{ nullptr };
		decltype(&CreateThread) CreateThread{ nullptr };
		decltype(&CreateThreadpool) CreateThreadpool{ nullptr };
		decltype(&CreateThreadpoolIo) CreateThreadpoolIo{ nullptr };
		decltype(&CreateThreadpoolTimer) CreateThreadpoolTimer{ nullptr };
		decltype(&CreateThreadpoolWait) CreateThreadpoolWait{ nullptr };
		decltype(&CreateThreadpoolWork) CreateThreadpoolWork{ nullptr };
		decltype(&CreateToolhelp32Snapshot) CreateToolhelp32Snapshot{ nullptr };
		decltype(&CreateWellKnownSid) CreateWellKnownSid{ nullptr };
		decltype(&CreateWindowExW) CreateWindowExW{ nullptr };
		decltype(&CryptCATAdminAcquireContext) CryptCATAdminAcquireContext{ nullptr };
		decltype(&CryptCATAdminAcquireContext2) CryptCATAdminAcquireContext2{ nullptr };
		decltype(&CryptCATAdminCalcHashFromFileHandle) CryptCATAdminCalcHashFromFileHandle{ nullptr };
		decltype(&CryptCATAdminCalcHashFromFileHandle2) CryptCATAdminCalcHashFromFileHandle2{ nullptr };
		decltype(&CryptCATAdminEnumCatalogFromHash) CryptCATAdminEnumCatalogFromHash{ nullptr };
		decltype(&CryptCATAdminReleaseCatalogContext) CryptCATAdminReleaseCatalogContext{ nullptr };
		decltype(&CryptCATAdminReleaseContext) CryptCATAdminReleaseContext{ nullptr };
		decltype(&CryptCATCatalogInfoFromContext) CryptCATCatalogInfoFromContext{ nullptr };
		decltype(&CryptDecodeObject) CryptDecodeObject{ nullptr };
		decltype(&CryptDecodeObjectEx) CryptDecodeObjectEx{ nullptr };
		decltype(&CryptFindOIDInfo) CryptFindOIDInfo{ nullptr };
		decltype(&CryptHashCertificate) CryptHashCertificate{ nullptr };
		decltype(&CryptHashCertificate2) CryptHashCertificate2{ nullptr };
		decltype(&CryptMsgClose) CryptMsgClose{ nullptr };
		decltype(&CryptMsgGetParam) CryptMsgGetParam{ nullptr };
		decltype(&CryptQueryObject) CryptQueryObject{ nullptr };
		decltype(&CryptVerifyMessageSignature) CryptVerifyMessageSignature{ nullptr };
		decltype(&D3D11CreateDeviceAndSwapChain) D3D11CreateDeviceAndSwapChain{ nullptr };
		decltype(&DebugBreak) DebugBreak{ nullptr };
		decltype(&DefWindowProcA) DefWindowProcA{ nullptr };
		decltype(&DefWindowProcW) DefWindowProcW{ nullptr };
		decltype(&DeleteCriticalSection) DeleteCriticalSection{ nullptr };
		decltype(&DeleteDC) DeleteDC{ nullptr };
		decltype(&DeleteFileA) DeleteFileA{ nullptr };
		decltype(&DeleteFileW) DeleteFileW{ nullptr };
		decltype(&DeleteObject) DeleteObject{ nullptr };
		decltype(&DeleteProcThreadAttributeList) DeleteProcThreadAttributeList{ nullptr };
		decltype(&DeleteService) DeleteService{ nullptr };
		decltype(&DestroyIcon) DestroyIcon{ nullptr };
		decltype(&DestroyMenu) DestroyMenu{ nullptr };
		decltype(&DestroyWindow) DestroyWindow{ nullptr };
		decltype(&DeviceIoControl) DeviceIoControl{ nullptr };
		decltype(&DisconnectNamedPipe) DisconnectNamedPipe{ nullptr };
		decltype(&DispatchMessageW) DispatchMessageW{ nullptr };
		decltype(&DnsFree) DnsFree{ nullptr };
		decltype(&DnsQuery_W) DnsQuery_W{ nullptr };
		decltype(&DrawFocusRect) DrawFocusRect{ nullptr };
		decltype(&DrawIconEx) DrawIconEx{ nullptr };
		decltype(&DrawTextW) DrawTextW{ nullptr };
		decltype(&DuplicateHandle) DuplicateHandle{ nullptr };
		decltype(&DuplicateToken) DuplicateToken{ nullptr };
		decltype(&DuplicateTokenEx) DuplicateTokenEx{ nullptr };
		decltype(&DwmEnableBlurBehindWindow) DwmEnableBlurBehindWindow{ nullptr };
		decltype(&DwmExtendFrameIntoClientArea) DwmExtendFrameIntoClientArea{ nullptr };
		decltype(&Ellipse) Ellipse{ nullptr };
		decltype(&EmptyClipboard) EmptyClipboard{ nullptr };
		decltype(&EmptyWorkingSet) EmptyWorkingSet{ nullptr };
		decltype(&EnableTraceEx2) EnableTraceEx2{ nullptr };
		decltype(&EnableWindow) EnableWindow{ nullptr };
		decltype(&EndPaint) EndPaint{ nullptr };
		decltype(&EnterCriticalSection) EnterCriticalSection{ nullptr };
		decltype(&EnumChildWindows) EnumChildWindows{ nullptr };
		decltype(&EnumClipboardFormats) EnumClipboardFormats{ nullptr };
		decltype(&EnumDesktopWindows) EnumDesktopWindows{ nullptr };
		decltype(&EnumDesktopsW) EnumDesktopsW{ nullptr };
		decltype(&EnumDeviceDrivers) EnumDeviceDrivers{ nullptr };
		decltype(&EnumDisplayDevicesW) EnumDisplayDevicesW{ nullptr };
		decltype(&EnumDisplayMonitors) EnumDisplayMonitors{ nullptr };
		decltype(&EnumDisplaySettingsW) EnumDisplaySettingsW{ nullptr };
		decltype(&EnumProcessModules) EnumProcessModules{ nullptr };
		decltype(&EnumProcesses) EnumProcesses{ nullptr };
		decltype(&EnumServicesStatusW) EnumServicesStatusW{ nullptr };
		decltype(&EnumSystemFirmwareTables) EnumSystemFirmwareTables{ nullptr };
		decltype(&EnumWindowStationsW) EnumWindowStationsW{ nullptr };
		decltype(&EnumWindows) EnumWindows{ nullptr };
		decltype(&EvtClose) EvtClose{ nullptr };
		decltype(&EvtCreateRenderContext) EvtCreateRenderContext{ nullptr };
		decltype(&EvtFormatMessage) EvtFormatMessage{ nullptr };
		decltype(&EvtNext) EvtNext{ nullptr };
		decltype(&EvtOpenPublisherMetadata) EvtOpenPublisherMetadata{ nullptr };
		decltype(&EvtQuery) EvtQuery{ nullptr };
		decltype(&EvtRender) EvtRender{ nullptr };
		decltype(&ExitThread) ExitThread{ nullptr };
		decltype(&ExitWindowsEx) ExitWindowsEx{ nullptr };
		decltype(&ExpandEnvironmentStringsW) ExpandEnvironmentStringsW{ nullptr };
		decltype(&ExtractIconExW) ExtractIconExW{ nullptr };
		decltype(&FatalAppExitW) FatalAppExitW{ nullptr };
		decltype(&FileTimeToLocalFileTime) FileTimeToLocalFileTime{ nullptr };
		decltype(&FileTimeToSystemTime) FileTimeToSystemTime{ nullptr };
		decltype(&FillRect) FillRect{ nullptr };
		decltype(&FilterConnectCommunicationPort) FilterConnectCommunicationPort{ nullptr };
		decltype(&FilterGetMessage) FilterGetMessage{ nullptr };
		decltype(&FilterReplyMessage) FilterReplyMessage{ nullptr };
		decltype(&FilterSendMessage) FilterSendMessage{ nullptr };
		decltype(&FindClose) FindClose{ nullptr };
		decltype(&FindFirstFileW) FindFirstFileW{ nullptr };
		decltype(&FindFirstVolumeW) FindFirstVolumeW{ nullptr };
		decltype(&FindNextFileW) FindNextFileW{ nullptr };
		decltype(&FindNextVolumeW) FindNextVolumeW{ nullptr };
		decltype(&FindResourceW) FindResourceW{ nullptr };
		decltype(&FindVolumeClose) FindVolumeClose{ nullptr };
		decltype(&FindWindowW) FindWindowW{ nullptr };
		decltype(&FindWindowExW) FindWindowExW{ nullptr };
		decltype(&FlushFileBuffers) FlushFileBuffers{ nullptr };
		decltype(&FormatMessageW) FormatMessageW{ nullptr };
		decltype(&FreeEnvironmentStringsW) FreeEnvironmentStringsW{ nullptr };
		decltype(&FreeLibrary) FreeLibrary{ nullptr };
		decltype(&FreeLibraryAndExitThread) FreeLibraryAndExitThread{ nullptr };
		decltype(&FreeSid) FreeSid{ nullptr };
		decltype(&FreeUserPhysicalPages) FreeUserPhysicalPages{ nullptr };
		decltype(&FtpPutFileW) FtpPutFileW{ nullptr };
		decltype(&GdiplusStartup) GdiplusStartup{ nullptr };
		decltype(&GdiplusShutdown) GdiplusShutdown{ nullptr };
		decltype(&GetACP) GetACP{ nullptr };
		decltype(&GetAce) GetAce{ nullptr };
		decltype(&GetActiveProcessorCount) GetActiveProcessorCount{ nullptr };
		decltype(&GetActiveWindow) GetActiveWindow{ nullptr };
		decltype(&GetAdaptersAddresses) GetAdaptersAddresses{ nullptr };
		decltype(&GetAdaptersInfo) GetAdaptersInfo{ nullptr };
		decltype(&GetBinaryTypeW) GetBinaryTypeW{ nullptr };
		decltype(&GetClassNameW) GetClassNameW{ nullptr };
		decltype(&GetClientRect) GetClientRect{ nullptr };
		decltype(&GetClipboardData) GetClipboardData{ nullptr };
		decltype(&GetClipboardFormatNameW) GetClipboardFormatNameW{ nullptr };
		decltype(&GetComboBoxInfo) GetComboBoxInfo{ nullptr };
		decltype(&GetCommandLineA) GetCommandLineA{ nullptr };
		decltype(&GetCommandLineW) GetCommandLineW{ nullptr };
		decltype(&GetComputerNameW) GetComputerNameW{ nullptr };
		decltype(&GetComputerNameExW) GetComputerNameExW{ nullptr };
		decltype(&GetConsoleWindow) GetConsoleWindow{ nullptr };
		decltype(&GetCurrentDirectoryW) GetCurrentDirectoryW{ nullptr };
		decltype(&GetCurrentHwProfileW) GetCurrentHwProfileW{ nullptr };
		decltype(&GetCurrentInputMessageSource) GetCurrentInputMessageSource{ nullptr };
		decltype(&GetCurrentProcess) GetCurrentProcess{ nullptr };
		decltype(&GetCurrentProcessId) GetCurrentProcessId{ nullptr };
		decltype(&GetCurrentThreadId) GetCurrentThreadId{ nullptr };
		decltype(&GetCursorPos) GetCursorPos{ nullptr };
		decltype(&GetDC) GetDC{ nullptr };
		decltype(&GetDCEx) GetDCEx{ nullptr };
		decltype(&GetDIBits) GetDIBits{ nullptr };
		decltype(&GetDesktopWindow) GetDesktopWindow{ nullptr };
		decltype(&GetDeviceCaps) GetDeviceCaps{ nullptr };
		decltype(&GetDeviceDriverBaseNameW) GetDeviceDriverBaseNameW{ nullptr };
		decltype(&GetDeviceDriverFileNameW) GetDeviceDriverFileNameW{ nullptr };
		decltype(&GetDiskFreeSpaceW) GetDiskFreeSpaceW{ nullptr };
		decltype(&GetDiskFreeSpaceExW) GetDiskFreeSpaceExW{ nullptr };
		decltype(&GetDlgItem) GetDlgItem{ nullptr };
		decltype(&GetDriveTypeW) GetDriveTypeW{ nullptr };
		decltype(&GetEnvironmentStringsW) GetEnvironmentStringsW{ nullptr };
		decltype(&GetEnvironmentVariableW) GetEnvironmentVariableW{ nullptr };
		decltype(&GetExitCodeProcess) GetExitCodeProcess{ nullptr };
		decltype(&GetExitCodeThread) GetExitCodeThread{ nullptr };
		decltype(&GetExtendedTcpTable) GetExtendedTcpTable{ nullptr };
		decltype(&GetExtendedUdpTable) GetExtendedUdpTable{ nullptr };
		decltype(&GetFileAttributesW) GetFileAttributesW{ nullptr };
		decltype(&GetFileAttributesExW) GetFileAttributesExW{ nullptr };
		decltype(&GetFileInformationByHandle) GetFileInformationByHandle{ nullptr };
		decltype(&GetFileSize) GetFileSize{ nullptr };
		decltype(&GetFileSizeEx) GetFileSizeEx{ nullptr };
		decltype(&GetFileTime) GetFileTime{ nullptr };
		decltype(&GetFileVersionInfoW) GetFileVersionInfoW{ nullptr };
		decltype(&GetFileVersionInfoSizeW) GetFileVersionInfoSizeW{ nullptr };
		decltype(&GetFinalPathNameByHandleW) GetFinalPathNameByHandleW{ nullptr };
		decltype(&GetFirmwareEnvironmentVariableW) GetFirmwareEnvironmentVariableW{ nullptr };
		decltype(&GetForegroundWindow) GetForegroundWindow{ nullptr };
		decltype(&GetGeoInfoW) GetGeoInfoW{ nullptr };
		decltype(&GetGuiResources) GetGuiResources{ nullptr };
		decltype(&GetHandleInformation) GetHandleInformation{ nullptr };
		decltype(&GetIconInfo) GetIconInfo{ nullptr };
		decltype(&GetIfTable) GetIfTable{ nullptr };
		decltype(&GetInterfaceInfo) GetInterfaceInfo{ nullptr };
		decltype(&GetIpAddrTable) GetIpAddrTable{ nullptr };
		decltype(&GetIpNetTable) GetIpNetTable{ nullptr };
		decltype(&GetKeyboardLayout) GetKeyboardLayout{ nullptr };
		decltype(&GetLastError) GetLastError{ nullptr };
		decltype(&GetLengthSid) GetLengthSid{ nullptr };
		decltype(&GetLocalTime) GetLocalTime{ nullptr };
		decltype(&GetLocaleInfoW) GetLocaleInfoW{ nullptr };
		decltype(&GetLocaleInfoEx) GetLocaleInfoEx{ nullptr };
		decltype(&GetLogicalDriveStringsW) GetLogicalDriveStringsW{ nullptr };
		decltype(&GetMailslotInfo) GetMailslotInfo{ nullptr };
		decltype(&GetMappedFileNameW) GetMappedFileNameW{ nullptr };
		decltype(&GetMenuItemInfoW) GetMenuItemInfoW{ nullptr };
		decltype(&GetMessageW) GetMessageW{ nullptr };
		decltype(&GetMessagePos) GetMessagePos{ nullptr };
		decltype(&GetModuleBaseNameW) GetModuleBaseNameW{ nullptr };
		decltype(&GetModuleFileNameW) GetModuleFileNameW{ nullptr };
		decltype(&GetModuleFileNameExW) GetModuleFileNameExW{ nullptr };
		decltype(&GetModuleHandleA) GetModuleHandleA{ nullptr };
		decltype(&GetModuleHandleExW) GetModuleHandleExW{ nullptr };
		decltype(&GetModuleInformation) GetModuleInformation{ nullptr };
		decltype(&GetMonitorInfoW) GetMonitorInfoW{ nullptr };
		decltype(&GetNamedPipeClientProcessId) GetNamedPipeClientProcessId{ nullptr };
		decltype(&GetNamedPipeHandleStateW) GetNamedPipeHandleStateW{ nullptr };
		decltype(&GetNamedPipeInfo) GetNamedPipeInfo{ nullptr };
		decltype(&GetNamedPipeServerProcessId) GetNamedPipeServerProcessId{ nullptr };
		decltype(&GetNativeSystemInfo) GetNativeSystemInfo{ nullptr };
		decltype(&GetOEMCP) GetOEMCP{ nullptr };
		decltype(&GetObjectW) GetObjectW{ nullptr };
		decltype(&GetParent) GetParent{ nullptr };
		decltype(&GetPerAdapterInfo) GetPerAdapterInfo{ nullptr };
		decltype(&GetPhysicallyInstalledSystemMemory) GetPhysicallyInstalledSystemMemory{ nullptr };
		decltype(&GetPriorityClass) GetPriorityClass{ nullptr };
		decltype(&GetProcessDEPPolicy) GetProcessDEPPolicy{ nullptr };
		decltype(&GetProcessHandleCount) GetProcessHandleCount{ nullptr };
		decltype(&GetProcessHeap) GetProcessHeap{ nullptr };
		decltype(&GetProcessId) GetProcessId{ nullptr };
		decltype(&GetProcessImageFileNameW) GetProcessImageFileNameW{ nullptr };
		decltype(&GetProcessMemoryInfo) GetProcessMemoryInfo{ nullptr };
		decltype(&GetProcessMitigationPolicy) GetProcessMitigationPolicy{ nullptr };
		decltype(&GetProcessShutdownParameters) GetProcessShutdownParameters{ nullptr };
		decltype(&GetProcessTimes) GetProcessTimes{ nullptr };
		decltype(&GetProcessWindowStation) GetProcessWindowStation{ nullptr };
		decltype(&GetProductInfo) GetProductInfo{ nullptr };
		decltype(&GetRawInputData) GetRawInputData{ nullptr };
		decltype(&GetRawInputDeviceInfoW) GetRawInputDeviceInfoW{ nullptr };
		decltype(&GetSecurityDescriptorDacl) GetSecurityDescriptorDacl{ nullptr };
		decltype(&GetSecurityInfo) GetSecurityInfo{ nullptr };
		decltype(&GetShellWindow) GetShellWindow{ nullptr };
		decltype(&GetSidIdentifierAuthority) GetSidIdentifierAuthority{ nullptr };
		decltype(&GetSidSubAuthority) GetSidSubAuthority{ nullptr };
		decltype(&GetSidSubAuthorityCount) GetSidSubAuthorityCount{ nullptr };
		decltype(&GetStartupInfoW) GetStartupInfoW{ nullptr };
		decltype(&GetStdHandle) GetStdHandle{ nullptr };
		decltype(&GetStockObject) GetStockObject{ nullptr };
		decltype(&GetSysColor) GetSysColor{ nullptr };
		decltype(&GetSystemDEPPolicy) GetSystemDEPPolicy{ nullptr };
		decltype(&GetSystemDefaultLCID) GetSystemDefaultLCID{ nullptr };
		decltype(&GetSystemDefaultLangID) GetSystemDefaultLangID{ nullptr };
		decltype(&GetSystemDefaultLocaleName) GetSystemDefaultLocaleName{ nullptr };
		decltype(&GetSystemDefaultUILanguage) GetSystemDefaultUILanguage{ nullptr };
		decltype(&GetSystemDirectoryW) GetSystemDirectoryW{ nullptr };
		decltype(&GetSystemFirmwareTable) GetSystemFirmwareTable{ nullptr };
		decltype(&GetSystemInfo) GetSystemInfo{ nullptr };
		decltype(&GetSystemMetrics) GetSystemMetrics{ nullptr };
		decltype(&GetSystemPowerStatus) GetSystemPowerStatus{ nullptr };
		decltype(&GetSystemRegistryQuota) GetSystemRegistryQuota{ nullptr };
		decltype(&GetSystemTime) GetSystemTime{ nullptr };
		decltype(&GetSystemTimeAdjustment) GetSystemTimeAdjustment{ nullptr };
		decltype(&GetSystemTimeAsFileTime) GetSystemTimeAsFileTime{ nullptr };
		decltype(&GetSystemTimes) GetSystemTimes{ nullptr };
		decltype(&GetSystemWow64DirectoryW) GetSystemWow64DirectoryW{ nullptr };
		decltype(&GetTempFileNameW) GetTempFileNameW{ nullptr };
		decltype(&GetTempPathW) GetTempPathW{ nullptr };
		decltype(&GetTextExtentPoint32W) GetTextExtentPoint32W{ nullptr };
		decltype(&GetThreadContext) GetThreadContext{ nullptr };
		decltype(&GetThreadDesktop) GetThreadDesktop{ nullptr };
		decltype(&GetThreadId) GetThreadId{ nullptr };
		decltype(&GetThreadLocale) GetThreadLocale{ nullptr };
		decltype(&GetThreadPriority) GetThreadPriority{ nullptr };
		decltype(&GetThreadTimes) GetThreadTimes{ nullptr };
		decltype(&GetTickCount) GetTickCount{ nullptr };
		decltype(&GetTickCount64) GetTickCount64{ nullptr };
		decltype(&GetTimeZoneInformation) GetTimeZoneInformation{ nullptr };
		decltype(&GetTimestampForLoadedLibrary) GetTimestampForLoadedLibrary{ nullptr };
		decltype(&GetTokenInformation) GetTokenInformation{ nullptr };
		decltype(&GetTopWindow) GetTopWindow{ nullptr };
		decltype(&GetUdpTable) GetUdpTable{ nullptr };
		decltype(&GetUserDefaultLCID) GetUserDefaultLCID{ nullptr };
		decltype(&GetUserDefaultLangID) GetUserDefaultLangID{ nullptr };
		decltype(&GetUserDefaultLocaleName) GetUserDefaultLocaleName{ nullptr };
		decltype(&GetUserDefaultUILanguage) GetUserDefaultUILanguage{ nullptr };
		decltype(&GetUserGeoID) GetUserGeoID{ nullptr };
		decltype(&GetUserNameW) GetUserNameW{ nullptr };
		decltype(&GetUserProfileDirectoryW) GetUserProfileDirectoryW{ nullptr };
		decltype(&GetVersion) GetVersion{ nullptr };
		decltype(&GetVersionExW) GetVersionExW{ nullptr };
		decltype(&GetVolumeInformationW) GetVolumeInformationW{ nullptr };
		decltype(&GetVolumePathNamesForVolumeNameA) GetVolumePathNamesForVolumeNameA{ nullptr };
		decltype(&GetVolumeNameForVolumeMountPointW) GetVolumeNameForVolumeMountPointW{ nullptr };
		decltype(&GetVolumePathNamesForVolumeNameW) GetVolumePathNamesForVolumeNameW{ nullptr };
		decltype(&GetWindow) GetWindow{ nullptr };
		decltype(&GetWindowDC) GetWindowDC{ nullptr };
		decltype(&GetWindowDisplayAffinity) GetWindowDisplayAffinity{ nullptr };
		decltype(&GetWindowInfo) GetWindowInfo{ nullptr };
		decltype(&GetWindowLongW) GetWindowLongW{ nullptr };
		decltype(&GetWindowModuleFileNameW) GetWindowModuleFileNameW{ nullptr };
		decltype(&GetWindowRect) GetWindowRect{ nullptr };
		decltype(&GetWindowTextW) GetWindowTextW{ nullptr };
		decltype(&GetWindowTextLengthW) GetWindowTextLengthW{ nullptr };
		decltype(&GetWindowThreadProcessId) GetWindowThreadProcessId{ nullptr };
		decltype(&GetWindowsDirectoryW) GetWindowsDirectoryW{ nullptr };
		decltype(&GetWriteWatch) GetWriteWatch{ nullptr };
		decltype(&GlobalAlloc) GlobalAlloc{ nullptr };
		decltype(&GlobalFree) GlobalFree{ nullptr };
		decltype(&GlobalGetAtomNameW) GlobalGetAtomNameW{ nullptr };
		decltype(&GlobalLock) GlobalLock{ nullptr };
		decltype(&GlobalMemoryStatusEx) GlobalMemoryStatusEx{ nullptr };
		decltype(&GlobalUnlock) GlobalUnlock{ nullptr };
		decltype(&HeapAlloc) HeapAlloc{ nullptr };
		decltype(&HeapCreate) HeapCreate{ nullptr };
		decltype(&HeapDestroy) HeapDestroy{ nullptr };
		decltype(&HeapFree) HeapFree{ nullptr };
		decltype(&HeapQueryInformation) HeapQueryInformation{ nullptr };
		decltype(&HeapReAlloc) HeapReAlloc{ nullptr };
		decltype(&HeapSetInformation) HeapSetInformation{ nullptr };
		decltype(&HideCaret) HideCaret{ nullptr };
		decltype(&HttpAddRequestHeadersW) HttpAddRequestHeadersW{ nullptr };
		decltype(&HttpEndRequestW) HttpEndRequestW{ nullptr };
		decltype(&HttpOpenRequestW) HttpOpenRequestW{ nullptr };
		decltype(&HttpQueryInfoW) HttpQueryInfoW{ nullptr };
		decltype(&HttpSendRequestExW) HttpSendRequestExW{ nullptr };
		decltype(&ILFree) ILFree{ nullptr };
		decltype(&ImmGetDescriptionW) ImmGetDescriptionW{ nullptr };
		decltype(&ImmIsIME) ImmIsIME{ nullptr };
		decltype(&ImpersonateLoggedOnUser) ImpersonateLoggedOnUser{ nullptr };
		decltype(&InflateRect) InflateRect{ nullptr };
		decltype(&InitializeAcl) InitializeAcl{ nullptr };
		decltype(&InitializeCriticalSection) InitializeCriticalSection{ nullptr };
		decltype(&InitializeProcThreadAttributeList) InitializeProcThreadAttributeList{ nullptr };
		decltype(&InitializeSecurityDescriptor) InitializeSecurityDescriptor{ nullptr };
		decltype(&InsertMenuW) InsertMenuW{ nullptr };
		decltype(&InsertMenuItemW) InsertMenuItemW{ nullptr };
		decltype(&InternalGetWindowText) InternalGetWindowText{ nullptr };
		decltype(&InternetAttemptConnect) InternetAttemptConnect{ nullptr };
		decltype(&InternetCheckConnectionW) InternetCheckConnectionW{ nullptr };
		decltype(&InternetCloseHandle) InternetCloseHandle{ nullptr };
		decltype(&InternetConnectW) InternetConnectW{ nullptr };
		decltype(&InternetGetConnectedState) InternetGetConnectedState{ nullptr };
		decltype(&InternetGetLastResponseInfoW) InternetGetLastResponseInfoW{ nullptr };
		decltype(&InternetOpenW) InternetOpenW{ nullptr };
		decltype(&InternetOpenUrlW) InternetOpenUrlW{ nullptr };
		decltype(&InternetReadFile) InternetReadFile{ nullptr };
		decltype(&InternetWriteFile) InternetWriteFile{ nullptr };
		decltype(&IntersectRect) IntersectRect{ nullptr };
		decltype(&InvalidateRect) InvalidateRect{ nullptr };
		decltype(&IsClipboardFormatAvailable) IsClipboardFormatAvailable{ nullptr };
		decltype(&IsDebuggerPresent) IsDebuggerPresent{ nullptr };
		decltype(&IsDialogMessageW) IsDialogMessageW{ nullptr };
		decltype(&IsHungAppWindow) IsHungAppWindow{ nullptr };
		decltype(&IsIconic) IsIconic{ nullptr };
		decltype(&IsNativeVhdBoot) IsNativeVhdBoot{ nullptr };
		decltype(&IsProcessorFeaturePresent) IsProcessorFeaturePresent{ nullptr };
		decltype(&IsRectEmpty) IsRectEmpty{ nullptr };
		decltype(&IsThreadpoolTimerSet) IsThreadpoolTimerSet{ nullptr };
		decltype(&IsValidSecurityDescriptor) IsValidSecurityDescriptor{ nullptr };
		decltype(&IsValidSid) IsValidSid{ nullptr };
		decltype(&IsUserAnAdmin) IsUserAnAdmin{ nullptr };
		decltype(&IsWindow) IsWindow{ nullptr };
		decltype(&IsWindowEnabled) IsWindowEnabled{ nullptr };
		decltype(&IsWindowUnicode) IsWindowUnicode{ nullptr };
		decltype(&IsWindowVisible) IsWindowVisible{ nullptr };
		decltype(&IsWow64Process) IsWow64Process{ nullptr };
		decltype(&IsWow64Process2) IsWow64Process2{ nullptr };
		decltype(&KillTimer) KillTimer{ nullptr };
		decltype(&LCIDToLocaleName) LCIDToLocaleName{ nullptr };
		decltype(&LdrFindEntryForAddress) LdrFindEntryForAddress{ nullptr };
		decltype(&LdrGetProcedureAddress) LdrGetProcedureAddress{ nullptr };
		decltype(&LdrLoadDll) LdrLoadDll{ nullptr };
		decltype(&LdrShutdownProcess) LdrShutdownProcess{ nullptr };
		decltype(&LeaveCriticalSection) LeaveCriticalSection{ nullptr };
		decltype(&LoadBitmapW) LoadBitmapW{ nullptr };
		decltype(&LoadCursorW) LoadCursorW{ nullptr };
		decltype(&LoadIconW) LoadIconW{ nullptr };
		decltype(&LoadLibraryA) LoadLibraryA{ nullptr };
		decltype(&LoadLibraryW) LoadLibraryW{ nullptr };
		decltype(&LoadLibraryExA) LoadLibraryExA{ nullptr };
		decltype(&LoadLibraryExW) LoadLibraryExW{ nullptr };
		decltype(&LoadResource) LoadResource{ nullptr };
		decltype(&LocalAlloc) LocalAlloc{ nullptr };
		decltype(&LocalFree) LocalFree{ nullptr };
		decltype(&LockResource) LockResource{ nullptr };
		decltype(&LookupAccountNameW) LookupAccountNameW{ nullptr };
		decltype(&LookupAccountSidW) LookupAccountSidW{ nullptr };
		decltype(&LookupPrivilegeDisplayNameW) LookupPrivilegeDisplayNameW{ nullptr };
		decltype(&LookupPrivilegeNameW) LookupPrivilegeNameW{ nullptr };
		decltype(&LookupPrivilegeValueW) LookupPrivilegeValueW{ nullptr };
		decltype(&LsaClose) LsaClose{ nullptr };
		decltype(&LsaEnumerateAccountRights) LsaEnumerateAccountRights{ nullptr };
		decltype(&LsaFreeMemory) LsaFreeMemory{ nullptr };
		decltype(&LsaNtStatusToWinError) LsaNtStatusToWinError{ nullptr };
		decltype(&LsaOpenPolicy) LsaOpenPolicy{ nullptr };
		decltype(&MapViewOfFile) MapViewOfFile{ nullptr };
		decltype(&MapViewOfFileEx) MapViewOfFileEx{ nullptr };
		decltype(&MapUserPhysicalPages) MapUserPhysicalPages{ nullptr };
		decltype(&MessageBoxA) MessageBoxA{ nullptr };
		decltype(&MessageBoxW) MessageBoxW{ nullptr };
		decltype(&MiniDumpWriteDump) MiniDumpWriteDump{ nullptr };
		decltype(&Module32FirstW) Module32FirstW{ nullptr };
		decltype(&Module32NextW) Module32NextW{ nullptr };
		decltype(&MoveFileW) MoveFileW{ nullptr };
		decltype(&MoveFileExW) MoveFileExW{ nullptr };
		decltype(&MsgWaitForMultipleObjects) MsgWaitForMultipleObjects{ nullptr };
		decltype(&MsiEnumProductsW) MsiEnumProductsW{ nullptr };
		decltype(&MsiGetProductInfoW) MsiGetProductInfoW{ nullptr };
		decltype(&MultiByteToWideChar) MultiByteToWideChar{ nullptr };
		decltype(&NetApiBufferFree) NetApiBufferFree{ nullptr };
		decltype(&NetShareEnum) NetShareEnum{ nullptr };
		decltype(&NetUserEnum) NetUserEnum{ nullptr };
		decltype(&NetUserGetInfo) NetUserGetInfo{ nullptr };
		decltype(&NetUserGetLocalGroups) NetUserGetLocalGroups{ nullptr };
		decltype(&NetWkstaGetInfo) NetWkstaGetInfo{ nullptr };
		decltype(&Netbios) Netbios{ nullptr };
		decltype(&NtAdjustPrivilegesToken) NtAdjustPrivilegesToken{ nullptr };
		decltype(&NtAllocateVirtualMemory) NtAllocateVirtualMemory{ nullptr };		
		decltype(&NtClose) NtClose{ nullptr };
		decltype(&NtCreateDebugObject) NtCreateDebugObject{ nullptr };
		decltype(&NtCreateFile) NtCreateFile{ nullptr };
		decltype(&NtCreateSection) NtCreateSection{ nullptr };
		decltype(&NtCreateSemaphore) NtCreateSemaphore{ nullptr };
		decltype(&NtDebugActiveProcess) NtDebugActiveProcess{ nullptr };
		decltype(&NtDelayExecution) NtDelayExecution{ nullptr };
		decltype(&NtDuplicateObject) NtDuplicateObject{ nullptr };
		decltype(&NtEnumerateBootEntries) NtEnumerateBootEntries{ nullptr };
		decltype(&NtEnumerateKey) NtEnumerateKey{ nullptr };
		decltype(&NtFlushInstructionCache) NtFlushInstructionCache{ nullptr };
		decltype(&NtFreeVirtualMemory) NtFreeVirtualMemory{ nullptr };
		decltype(&NtGetContextThread) NtGetContextThread{ nullptr };
		decltype(&NtIsProcessInJob) NtIsProcessInJob{ nullptr };
		decltype(&NtLoadDriver) NtLoadDriver{ nullptr };
		decltype(&NtLockVirtualMemory) NtLockVirtualMemory{ nullptr };
		decltype(&NtMapViewOfSection) NtMapViewOfSection{ nullptr };
		decltype(&NtOpenDirectoryObject) NtOpenDirectoryObject{ nullptr };
		decltype(&NtOpenFile) NtOpenFile{ nullptr };
		decltype(&NtOpenKey) NtOpenKey{ nullptr };
		decltype(&NtOpenProcess) NtOpenProcess{ nullptr };
		decltype(&NtOpenProcessToken) NtOpenProcessToken{ nullptr };
		decltype(&NtOpenSection) NtOpenSection{ nullptr };
		decltype(&NtOpenSemaphore) NtOpenSemaphore{ nullptr };
		decltype(&NtOpenSymbolicLinkObject) NtOpenSymbolicLinkObject{ nullptr };
		decltype(&NtOpenThread) NtOpenThread{ nullptr };
		decltype(&NtOpenThreadToken) NtOpenThreadToken{ nullptr };
		decltype(&NtOpenTimer) NtOpenTimer{ nullptr };
		decltype(&NtProtectVirtualMemory) NtProtectVirtualMemory{ nullptr };
		decltype(&NtQueryBootEntryOrder) NtQueryBootEntryOrder{ nullptr };
		decltype(&NtQueryBootOptions) NtQueryBootOptions{ nullptr };
		decltype(&NtQueryDirectoryFile) NtQueryDirectoryFile{ nullptr };
		decltype(&NtQueryDirectoryObject) NtQueryDirectoryObject{ nullptr };
		decltype(&NtQueryInformationFile) NtQueryInformationFile{ nullptr };
		decltype(&NtQueryInformationProcess) NtQueryInformationProcess{ nullptr };
		decltype(&NtQueryInformationThread) NtQueryInformationThread{ nullptr };
		decltype(&NtQueryInformationToken) NtQueryInformationToken{ nullptr };
		decltype(&NtQuerySystemEnvironmentValueEx) NtQuerySystemEnvironmentValueEx{ nullptr };
		decltype(&NtQueryKey) NtQueryKey{ nullptr };
		decltype(&NtQueryLicenseValue) NtQueryLicenseValue{ nullptr };
		decltype(&NtQueryObject) NtQueryObject{ nullptr };
		decltype(&NtQuerySection) NtQuerySection{ nullptr };
		decltype(&NtQuerySecurityObject) NtQuerySecurityObject{ nullptr };
		decltype(&NtQuerySemaphore) NtQuerySemaphore{ nullptr };
		decltype(&NtQuerySymbolicLinkObject) NtQuerySymbolicLinkObject{ nullptr };
		decltype(&NtQuerySystemInformation) NtQuerySystemInformation{ nullptr };
		decltype(&NtQueryTimer) NtQueryTimer{ nullptr };
		decltype(&NtQueryVirtualMemory) NtQueryVirtualMemory{ nullptr };
		decltype(&NtRaiseHardError) NtRaiseHardError{ nullptr };
		decltype(&NtReadFile) NtReadFile{ nullptr };
		decltype(&NtReadVirtualMemory) NtReadVirtualMemory{ nullptr };
		decltype(&NtRemoveProcessDebug) NtRemoveProcessDebug{ nullptr };
		decltype(&NtResumeProcess) NtResumeProcess{ nullptr };
		decltype(&NtResumeThread) NtResumeThread{ nullptr };
		decltype(&NtSetContextThread) NtSetContextThread{ nullptr };
		decltype(&NtSetDebugFilterState) NtSetDebugFilterState{ nullptr };
		decltype(&NtSetInformationDebugObject) NtSetInformationDebugObject{ nullptr };
		decltype(&NtSetInformationProcess) NtSetInformationProcess{ nullptr };
		decltype(&NtSetInformationThread) NtSetInformationThread{ nullptr };
		decltype(&NtSetSystemInformation) NtSetSystemInformation{ nullptr };
		decltype(&NtSuspendProcess) NtSuspendProcess{ nullptr };
		decltype(&NtSuspendThread) NtSuspendThread{ nullptr };
		decltype(&NtSystemDebugControl) NtSystemDebugControl{ nullptr };
		decltype(&NtTerminateProcess) NtTerminateProcess{ nullptr };
		decltype(&NtTerminateThread) NtTerminateThread{ nullptr };
		decltype(&NtUnloadDriver) NtUnloadDriver{ nullptr };
		decltype(&NtUnlockVirtualMemory) NtUnlockVirtualMemory{ nullptr };
		decltype(&NtUnmapViewOfSection) NtUnmapViewOfSection{ nullptr };
		decltype(&NtWaitForSingleObject) NtWaitForSingleObject{ nullptr };
		decltype(&NtWriteVirtualMemory) NtWriteVirtualMemory{ nullptr };
		decltype(&NtYieldExecution) NtYieldExecution{ nullptr };
		decltype(&OffsetRect) OffsetRect{ nullptr };
		decltype(&OpenClipboard) OpenClipboard{ nullptr };
		decltype(&OpenDesktopW) OpenDesktopW{ nullptr };
		decltype(&OpenEventW) OpenEventW{ nullptr };
		decltype(&OpenFileMappingW) OpenFileMappingW{ nullptr };
		decltype(&OpenJobObjectW) OpenJobObjectW{ nullptr };
		decltype(&OpenMutexW) OpenMutexW{ nullptr };
		decltype(&OpenProcess) OpenProcess{ nullptr };
		decltype(&OpenProcessToken) OpenProcessToken{ nullptr };
		decltype(&OpenSCManagerW) OpenSCManagerW{ nullptr };
		decltype(&OpenSemaphoreW) OpenSemaphoreW{ nullptr };
		decltype(&OpenServiceW) OpenServiceW{ nullptr };
		decltype(&OpenThread) OpenThread{ nullptr };
		decltype(&OpenThreadToken) OpenThreadToken{ nullptr };
		decltype(&OpenTraceW) OpenTraceW{ nullptr };
		decltype(&OpenWindowStationW) OpenWindowStationW{ nullptr };
		decltype(&OutputDebugStringW) OutputDebugStringW{ nullptr };
		decltype(&PathFileExistsW) PathFileExistsW{ nullptr };
		decltype(&PathIsNetworkPathW) PathIsNetworkPathW{ nullptr };
		decltype(&PathIsUNCW) PathIsUNCW{ nullptr };
		decltype(&PeekMessageW) PeekMessageW{ nullptr };
		decltype(&PeekNamedPipe) PeekNamedPipe{ nullptr };
		decltype(&PostMessageW) PostMessageW{ nullptr };
		decltype(&PostQuitMessage) PostQuitMessage{ nullptr };
		decltype(&PostThreadMessageW) PostThreadMessageW{ nullptr };
		decltype(&Process32FirstW) Process32FirstW{ nullptr };
		decltype(&Process32NextW) Process32NextW{ nullptr };
		decltype(&ProcessIdToSessionId) ProcessIdToSessionId{ nullptr };
		decltype(&ProcessTrace) ProcessTrace{ nullptr };
		decltype(&PssCaptureSnapshot) PssCaptureSnapshot{ nullptr };
		decltype(&PssFreeSnapshot) PssFreeSnapshot{ nullptr };
		decltype(&PssQuerySnapshot) PssQuerySnapshot{ nullptr };
		decltype(&PssWalkMarkerCreate) PssWalkMarkerCreate{ nullptr };
		decltype(&PssWalkMarkerFree) PssWalkMarkerFree{ nullptr };
		decltype(&PssWalkSnapshot) PssWalkSnapshot{ nullptr };
		decltype(&PtInRect) PtInRect{ nullptr };
		decltype(&QueryDosDeviceW) QueryDosDeviceW{ nullptr };
		decltype(&QueryFullProcessImageNameW) QueryFullProcessImageNameW{ nullptr };
		decltype(&QueryServiceConfigW) QueryServiceConfigW{ nullptr };
		decltype(&QueryServiceObjectSecurity) QueryServiceObjectSecurity{ nullptr };
		decltype(&QueryServiceStatus) QueryServiceStatus{ nullptr };
		decltype(&QueryServiceStatusEx) QueryServiceStatusEx{ nullptr };
		decltype(&QueryThreadCycleTime) QueryThreadCycleTime{ nullptr };
		decltype(&QueryWorkingSet) QueryWorkingSet{ nullptr };
		decltype(&QueryWorkingSetEx) QueryWorkingSetEx{ nullptr };
		decltype(&RaiseException) RaiseException{ nullptr };
		decltype(&ReadFile) ReadFile{ nullptr };
		decltype(&ReadProcessMemory) ReadProcessMemory{ nullptr };
		decltype(&Rectangle) Rectangle{ nullptr };
		decltype(&RedrawWindow) RedrawWindow{ nullptr };
		decltype(&RegCloseKey) RegCloseKey{ nullptr };
		decltype(&RegCreateKeyW) RegCreateKeyW{ nullptr };
		decltype(&RegCreateKeyExW) RegCreateKeyExW{ nullptr };
		decltype(&RegDeleteKeyW) RegDeleteKeyW{ nullptr };
		decltype(&RegDeleteKeyExW) RegDeleteKeyExW{ nullptr };
		decltype(&RegDeleteTreeW) RegDeleteTreeW{ nullptr };
		decltype(&RegEnumKeyW) RegEnumKeyW{ nullptr };
		decltype(&RegEnumKeyExW) RegEnumKeyExW{ nullptr };
		decltype(&RegEnumValueW) RegEnumValueW{ nullptr };
		decltype(&RegGetValueW) RegGetValueW{ nullptr };
		decltype(&RegOpenKeyW) RegOpenKeyW{ nullptr };
		decltype(&RegOpenKeyExW) RegOpenKeyExW{ nullptr };
		decltype(&RegQueryInfoKeyW) RegQueryInfoKeyW{ nullptr };
		decltype(&RegQueryValueExW) RegQueryValueExW{ nullptr };
		decltype(&RegSetValueExW) RegSetValueExW{ nullptr };
		decltype(&RegisterClassW) RegisterClassW{ nullptr };
		decltype(&RegisterClassExW) RegisterClassExW{ nullptr };
		decltype(&RegisterDeviceNotificationW) RegisterDeviceNotificationW{ nullptr };
		decltype(&RegisterRawInputDevices) RegisterRawInputDevices{ nullptr };
		decltype(&RegisterWaitForSingleObject) RegisterWaitForSingleObject{ nullptr };
		decltype(&ReleaseCapture) ReleaseCapture{ nullptr };
		decltype(&ReleaseDC) ReleaseDC{ nullptr };
		decltype(&ReleaseMutex) ReleaseMutex{ nullptr };
		decltype(&RemoveDirectoryW) RemoveDirectoryW{ nullptr };
		decltype(&RemoveMenu) RemoveMenu{ nullptr };
		decltype(&RemoveVectoredContinueHandler) RemoveVectoredContinueHandler{ nullptr };
		decltype(&RemoveVectoredExceptionHandler) RemoveVectoredExceptionHandler{ nullptr };
		decltype(&ResetEvent) ResetEvent{ nullptr };
		decltype(&ResumeThread) ResumeThread{ nullptr };
		decltype(&RevertToSelf) RevertToSelf{ nullptr };
		decltype(&RoundRect) RoundRect{ nullptr };
		decltype(&RtlAcquirePrivilege) RtlAcquirePrivilege{ nullptr };
		decltype(&RtlAddAccessAllowedAce) RtlAddAccessAllowedAce{ nullptr };
		decltype(&RtlAddAccessDeniedAce) RtlAddAccessDeniedAce{ nullptr };
		decltype(&RtlAdjustPrivilege) RtlAdjustPrivilege{ nullptr };
		decltype(&RtlAllocateAndInitializeSid) RtlAllocateAndInitializeSid{ nullptr };
		decltype(&RtlAllocateHeap) RtlAllocateHeap{ nullptr };
		decltype(&RtlAnsiStringToUnicodeString) RtlAnsiStringToUnicodeString{ nullptr };
		decltype(&RtlCaptureContext) RtlCaptureContext{ nullptr };
		decltype(&RtlCaptureStackBackTrace) RtlCaptureStackBackTrace{ nullptr };
		decltype(&RtlCompareMemory) RtlCompareMemory{ nullptr };
		decltype(&RtlComputeCrc32) RtlComputeCrc32{ nullptr };
		decltype(&RtlCreateQueryDebugBuffer) RtlCreateQueryDebugBuffer{ nullptr };
		decltype(&RtlCreateTimer) RtlCreateTimer{ nullptr };
		decltype(&RtlCreateTimerQueue) RtlCreateTimerQueue{ nullptr };
		decltype(&RtlCreateUserThread) RtlCreateUserThread{ nullptr };
		decltype(&RtlDeleteTimer) RtlDeleteTimer{ nullptr };
		decltype(&RtlDeleteTimerQueue) RtlDeleteTimerQueue{ nullptr };
		decltype(&RtlDeregisterSecureMemoryCacheCallback) RtlDeregisterSecureMemoryCacheCallback{ nullptr };
		decltype(&RtlDestroyQueryDebugBuffer) RtlDestroyQueryDebugBuffer{ nullptr };
		decltype(&RtlFlushSecureMemoryCache) RtlFlushSecureMemoryCache{ nullptr };
		decltype(&RtlFreeAnsiString) RtlFreeAnsiString{ nullptr };
		decltype(&RtlFreeHeap) RtlFreeHeap{ nullptr };
		decltype(&RtlFreeUnicodeString) RtlFreeUnicodeString{ nullptr };
		decltype(&RtlGetAce) RtlGetAce{ nullptr };
		decltype(&RtlGetFrame) RtlGetFrame{ nullptr };
		decltype(&RtlGetNtVersionNumbers) RtlGetNtVersionNumbers{ nullptr };
		decltype(&RtlGetSaclSecurityDescriptor) RtlGetSaclSecurityDescriptor{ nullptr };
		decltype(&RtlGetVersion) RtlGetVersion{ nullptr };
		decltype(&RtlImageDirectoryEntryToData) RtlImageDirectoryEntryToData{ nullptr };
		decltype(&RtlImageNtHeader) RtlImageNtHeader{ nullptr };
		decltype(&RtlImageNtHeaderEx) RtlImageNtHeaderEx{ nullptr };
		decltype(&RtlInitAnsiString) RtlInitAnsiString{ nullptr };
		decltype(&RtlInitUnicodeString) RtlInitUnicodeString{ nullptr };
		decltype(&RtlInitUnicodeStringEx) RtlInitUnicodeStringEx{ nullptr };
		decltype(&RtlNtStatusToDosError) RtlNtStatusToDosError{ nullptr };
		decltype(&RtlPcToFileHeader) RtlPcToFileHeader{ nullptr };
		decltype(&RtlQueryProcessDebugInformation) RtlQueryProcessDebugInformation{ nullptr };
		decltype(&RtlRegisterSecureMemoryCacheCallback) RtlRegisterSecureMemoryCacheCallback{ nullptr };
		decltype(&RtlReleasePrivilege) RtlReleasePrivilege{ nullptr };
		decltype(&RtlSecondsSince1970ToTime) RtlSecondsSince1970ToTime{ nullptr };
		decltype(&SHFileOperationW) SHFileOperationW{ nullptr };
		decltype(&SHFormatDateTimeW) SHFormatDateTimeW{ nullptr };
		decltype(&SHGetFolderPathW) SHGetFolderPathW{ nullptr };
		decltype(&SHGetKnownFolderPath) SHGetKnownFolderPath{ nullptr };
		decltype(&SHGetSpecialFolderPathW) SHGetSpecialFolderPathW{ nullptr };
		decltype(&SHOpenFolderAndSelectItems) SHOpenFolderAndSelectItems{ nullptr };
		decltype(&SHParseDisplayName) SHParseDisplayName{ nullptr };
		decltype(&SLIsGenuineLocal) SLIsGenuineLocal{ nullptr };
		decltype(&SRSetRestorePointW) SRSetRestorePointW{ nullptr };
		decltype(&ScreenToClient) ScreenToClient{ nullptr };
		decltype(&ScrollWindowEx) ScrollWindowEx{ nullptr };
		decltype(&SelectObject) SelectObject{ nullptr };
		decltype(&SendMessageW) SendMessageW{ nullptr };
		decltype(&SetBkColor) SetBkColor{ nullptr };
		decltype(&SetBkMode) SetBkMode{ nullptr };
		decltype(&SetCapture) SetCapture{ nullptr };
		decltype(&SetClipboardData) SetClipboardData{ nullptr };
		decltype(&SetConsoleCtrlHandler) SetConsoleCtrlHandler{ nullptr };
		decltype(&SetCurrentDirectoryW) SetCurrentDirectoryW{ nullptr };
		decltype(&SetCursor) SetCursor{ nullptr };
		decltype(&SetDCBrushColor) SetDCBrushColor{ nullptr };
		decltype(&SetEntriesInAclW) SetEntriesInAclW{ nullptr };
		decltype(&SetErrorMode) SetErrorMode{ nullptr };
		decltype(&SetEvent) SetEvent{ nullptr };
		decltype(&SetFileAttributesW) SetFileAttributesW{ nullptr };
		decltype(&SetFileInformationByHandle) SetFileInformationByHandle{ nullptr };
		decltype(&SetFilePointer) SetFilePointer{ nullptr };
		decltype(&SetFilePointerEx) SetFilePointerEx{ nullptr };
		decltype(&SetFocus) SetFocus{ nullptr };
		decltype(&SetForegroundWindow) SetForegroundWindow{ nullptr };
		decltype(&SetHandleInformation) SetHandleInformation{ nullptr };
		decltype(&SetInformationJobObject) SetInformationJobObject{ nullptr };
		decltype(&SetKernelObjectSecurity) SetKernelObjectSecurity{ nullptr };
		decltype(&SetLastError) SetLastError{ nullptr };
		decltype(&SetLayeredWindowAttributes) SetLayeredWindowAttributes{ nullptr };
		decltype(&SetMenuItemInfoW) SetMenuItemInfoW{ nullptr };
		decltype(&SetNamedPipeHandleState) SetNamedPipeHandleState{ nullptr };
		decltype(&SetNamedSecurityInfoW) SetNamedSecurityInfoW{ nullptr };
		decltype(&SetPriorityClass) SetPriorityClass{ nullptr };
		decltype(&SetProcessDpiAwarenessContext) SetProcessDpiAwarenessContext{ nullptr };
		decltype(&SetProcessMitigationPolicy) SetProcessMitigationPolicy{ nullptr };
		decltype(&SetProcessShutdownParameters) SetProcessShutdownParameters{ nullptr };
		decltype(&SetProcessWindowStation) SetProcessWindowStation{ nullptr };
		decltype(&SetRectEmpty) SetRectEmpty{ nullptr };
		decltype(&SetSecurityDescriptorDacl) SetSecurityDescriptorDacl{ nullptr };
		decltype(&SetSecurityDescriptorGroup) SetSecurityDescriptorGroup{ nullptr };
		decltype(&SetSecurityDescriptorOwner) SetSecurityDescriptorOwner{ nullptr };
		decltype(&SetSecurityInfo) SetSecurityInfo{ nullptr };
		decltype(&SetServiceObjectSecurity) SetServiceObjectSecurity{ nullptr };
		decltype(&SetTextColor) SetTextColor{ nullptr };
		decltype(&SetThreadContext) SetThreadContext{ nullptr };
		decltype(&SetThreadDescription) SetThreadDescription{ nullptr };
		decltype(&SetThreadDesktop) SetThreadDesktop{ nullptr };
		decltype(&SetThreadPriority) SetThreadPriority{ nullptr };
		decltype(&SetTimer) SetTimer{ nullptr };
		decltype(&SetUnhandledExceptionFilter) SetUnhandledExceptionFilter{ nullptr };
		decltype(&SetWinEventHook) SetWinEventHook{ nullptr };
		decltype(&SetWindowDisplayAffinity) SetWindowDisplayAffinity{ nullptr };
		decltype(&SetWindowLongA) SetWindowLongA{ nullptr };
		decltype(&SetWindowLongW) SetWindowLongW{ nullptr };
		decltype(&SetWindowOrgEx) SetWindowOrgEx{ nullptr };
		decltype(&SetWindowPos) SetWindowPos{ nullptr };
		decltype(&SetWindowTextW) SetWindowTextW{ nullptr };
		decltype(&SetWindowTheme) SetWindowTheme{ nullptr };
		decltype(&SetWindowsHookExW) SetWindowsHookExW{ nullptr };
		decltype(&SetupDiCreateDeviceInfoListExA) SetupDiCreateDeviceInfoListExA{ nullptr };
		decltype(&SetupDiCreateDeviceInfoListExW) SetupDiCreateDeviceInfoListExW{ nullptr };
		decltype(&SetupDiDestroyDeviceInfoList) SetupDiDestroyDeviceInfoList{ nullptr };
		decltype(&SetupDiEnumDeviceInfo) SetupDiEnumDeviceInfo{ nullptr };
		decltype(&SetupDiEnumDeviceInterfaces) SetupDiEnumDeviceInterfaces{ nullptr };
		decltype(&SetupDiGetClassDevsW) SetupDiGetClassDevsW{ nullptr };
		decltype(&SetupDiGetClassDevsExA) SetupDiGetClassDevsExA{ nullptr };
		decltype(&SetupDiGetClassDevsExW) SetupDiGetClassDevsExW{ nullptr };
		decltype(&SetupDiGetDeviceInstanceIdW) SetupDiGetDeviceInstanceIdW{ nullptr };
		decltype(&SetupDiGetDeviceInterfaceDetailW) SetupDiGetDeviceInterfaceDetailW{ nullptr };
		decltype(&SetupDiGetDeviceRegistryPropertyW) SetupDiGetDeviceRegistryPropertyW{ nullptr };
		decltype(&SetupDiOpenDevRegKey) SetupDiOpenDevRegKey{ nullptr };
		decltype(&ShellExecuteW) ShellExecuteW{ nullptr };
		decltype(&ShellExecuteExW) ShellExecuteExW{ nullptr };
		decltype(&Shell_NotifyIconW) Shell_NotifyIconW{ nullptr };
		decltype(&SHGetFileInfoW) SHGetFileInfoW{ nullptr };
		decltype(&ShowCaret) ShowCaret{ nullptr };
		decltype(&ShowWindow) ShowWindow{ nullptr };
		decltype(&ShowWindowAsync) ShowWindowAsync{ nullptr };
		decltype(&ShutdownBlockReasonCreate) ShutdownBlockReasonCreate{ nullptr };
		decltype(&ShutdownBlockReasonDestroy) ShutdownBlockReasonDestroy{ nullptr };
		decltype(&SHQueryUserNotificationState) SHQueryUserNotificationState{ nullptr };
		decltype(&SizeofResource) SizeofResource{ nullptr };
		decltype(&Sleep) Sleep{ nullptr };
		decltype(&SleepEx) SleepEx{ nullptr };
		decltype(&SnmpExtensionInit) SnmpExtensionInit{ nullptr };
		decltype(&SnmpExtensionInitEx) SnmpExtensionInitEx{ nullptr };
		decltype(&SnmpExtensionQuery) SnmpExtensionQuery{ nullptr };
		decltype(&SnmpExtensionTrap) SnmpExtensionTrap{ nullptr };
		decltype(&SnmpUtilMemAlloc) SnmpUtilMemAlloc{ nullptr };
		decltype(&SnmpUtilOidCpy) SnmpUtilOidCpy{ nullptr };
		decltype(&SnmpUtilOidNCmp) SnmpUtilOidNCmp{ nullptr };
		decltype(&SnmpUtilVarBindFree) SnmpUtilVarBindFree{ nullptr };
		decltype(&StackWalk64) StackWalk64{ nullptr };
		decltype(&StartServiceW) StartServiceW{ nullptr };
		decltype(&StartThreadpoolIo) StartThreadpoolIo{ nullptr };
		decltype(&StartTraceW) StartTraceW{ nullptr };
		decltype(&StringFromCLSID) StringFromCLSID{ nullptr };
		decltype(&StringFromGUID2) StringFromGUID2{ nullptr };
		decltype(&SubmitThreadpoolWork) SubmitThreadpoolWork{ nullptr };
		decltype(&SuspendThread) SuspendThread{ nullptr };
		decltype(&SymCleanup) SymCleanup{ nullptr };
		decltype(&SymFromAddr) SymFromAddr{ nullptr };
		decltype(&SymFunctionTableAccess64) SymFunctionTableAccess64{ nullptr };
		decltype(&SymGetLineFromAddr64) SymGetLineFromAddr64{ nullptr };
		decltype(&SymGetModuleBase64) SymGetModuleBase64{ nullptr };
		decltype(&SymGetModuleInfo64) SymGetModuleInfo64{ nullptr };
		decltype(&SymGetModuleInfoW64) SymGetModuleInfoW64{ nullptr };
		decltype(&SymGetOptions) SymGetOptions{ nullptr };
		decltype(&SymGetSearchPathW) SymGetSearchPathW{ nullptr };
#ifndef _WIN64
		decltype(&SymGetSymFromAddr) SymGetSymFromAddr{ nullptr };
#endif
		decltype(&SymGetSymFromAddr64) SymGetSymFromAddr64{ nullptr };
		decltype(&SymGetTypeFromName) SymGetTypeFromName{ nullptr };
		decltype(&SymGetTypeFromNameW) SymGetTypeFromNameW{ nullptr };
		decltype(&SymGetTypeInfo) SymGetTypeInfo{ nullptr };
		decltype(&SymInitialize) SymInitialize{ nullptr };
		decltype(&SymInitializeW) SymInitializeW{ nullptr };
		decltype(&SymLoadModuleEx) SymLoadModuleEx{ nullptr };
		decltype(&SymLoadModuleExW) SymLoadModuleExW{ nullptr };
		decltype(&SymSetOptions) SymSetOptions{ nullptr };
		decltype(&SymSetSearchPathW) SymSetSearchPathW{ nullptr };
		decltype(&SymSrvGetFileIndexInfoW) SymSrvGetFileIndexInfoW{ nullptr };
		decltype(&SymUnloadModule64) SymUnloadModule64{ nullptr };
		decltype(&SysAllocString) SysAllocString{ nullptr };
		decltype(&SysFreeString) SysFreeString{ nullptr };
		decltype(&SysStringLen) SysStringLen{ nullptr };
		decltype(&SystemParametersInfoW) SystemParametersInfoW{ nullptr };
		decltype(&SystemTimeToFileTime) SystemTimeToFileTime{ nullptr };
		decltype(&Tbsi_GetDeviceInfo) Tbsi_GetDeviceInfo{ nullptr };
		decltype(&TdhEnumerateProviders) TdhEnumerateProviders{ nullptr };
		decltype(&TdhGetEventInformation) TdhGetEventInformation{ nullptr };
		decltype(&TdhGetProperty) TdhGetProperty{ nullptr };
		decltype(&TdhGetPropertySize) TdhGetPropertySize{ nullptr };
		decltype(&TerminateJobObject) TerminateJobObject{ nullptr };
		decltype(&TerminateProcess) TerminateProcess{ nullptr };
		decltype(&TerminateThread) TerminateThread{ nullptr };
		decltype(&Thread32First) Thread32First{ nullptr };
		decltype(&Thread32Next) Thread32Next{ nullptr };
		decltype(&Toolhelp32ReadProcessMemory) Toolhelp32ReadProcessMemory{ nullptr };
		decltype(&TrackMouseEvent) TrackMouseEvent{ nullptr };
		decltype(&TrackPopupMenu) TrackPopupMenu{ nullptr };
		decltype(&TransactNamedPipe) TransactNamedPipe{ nullptr };
		decltype(&TranslateMessage) TranslateMessage{ nullptr };
		decltype(&UnhookWinEvent) UnhookWinEvent{ nullptr };
		decltype(&UnhookWindowsHookEx) UnhookWindowsHookEx{ nullptr };
		decltype(&UnionRect) UnionRect{ nullptr };
		decltype(&UnmapViewOfFile) UnmapViewOfFile{ nullptr };
		decltype(&UnregisterClassW) UnregisterClassW{ nullptr };
		decltype(&UnregisterWait) UnregisterWait{ nullptr };
		decltype(&UpdateProcThreadAttribute) UpdateProcThreadAttribute{ nullptr };
		decltype(&UpdateWindow) UpdateWindow{ nullptr };
		decltype(&UuidFromStringW) UuidFromStringW{ nullptr };
		decltype(&VerLanguageNameW) VerLanguageNameW{ nullptr };
		decltype(&VerQueryValueW) VerQueryValueW{ nullptr };
		decltype(&VerSetConditionMask) VerSetConditionMask{ nullptr };
		decltype(&VerifyVersionInfoW) VerifyVersionInfoW{ nullptr };
		decltype(&VirtualAlloc) VirtualAlloc{ nullptr };
		decltype(&VirtualAllocEx) VirtualAllocEx{ nullptr };
		decltype(&VirtualFree) VirtualFree{ nullptr };
		decltype(&VirtualLock) VirtualLock{ nullptr };
		decltype(&VirtualProtect) VirtualProtect{ nullptr };
		decltype(&VirtualProtectEx) VirtualProtectEx{ nullptr };
		decltype(&VirtualQuery) VirtualQuery{ nullptr };
		decltype(&VirtualQueryEx) VirtualQueryEx{ nullptr };
		decltype(&VirtualUnlock) VirtualUnlock{ nullptr };
		decltype(&WICConvertBitmapSource) WICConvertBitmapSource{ nullptr };
		decltype(&WNetGetProviderNameW) WNetGetProviderNameW{ nullptr };
		decltype(&WSACleanup) WSACleanup{ nullptr };
		decltype(&WSAGetLastError) WSAGetLastError{ nullptr };
		decltype(&WSASetLastError) WSASetLastError{ nullptr };
		decltype(&WSAStartup) WSAStartup{ nullptr };
		decltype(&WTHelperGetProvCertFromChain) WTHelperGetProvCertFromChain{ nullptr };
		decltype(&WTHelperGetProvSignerFromChain) WTHelperGetProvSignerFromChain{ nullptr };
		decltype(&WTHelperProvDataFromStateData) WTHelperProvDataFromStateData{ nullptr };
		decltype(&WTSCloseServer) WTSCloseServer{ nullptr };
		decltype(&WTSDisconnectSession) WTSDisconnectSession{ nullptr };
		decltype(&WTSEnumerateProcessesW) WTSEnumerateProcessesW{ nullptr };
		decltype(&WTSEnumerateSessionsW) WTSEnumerateSessionsW{ nullptr };
		decltype(&WTSFreeMemory) WTSFreeMemory{ nullptr };
		decltype(&WTSGetActiveConsoleSessionId) WTSGetActiveConsoleSessionId{ nullptr };
		decltype(&WTSLogoffSession) WTSLogoffSession{ nullptr };
		decltype(&WTSOpenServerW) WTSOpenServerW{ nullptr };
		decltype(&WTSQuerySessionInformationW) WTSQuerySessionInformationW{ nullptr };
		decltype(&WTSQueryUserToken) WTSQueryUserToken{ nullptr };
		decltype(&WaitForMultipleObjects) WaitForMultipleObjects{ nullptr };
		decltype(&WaitForSingleObject) WaitForSingleObject{ nullptr };
		decltype(&WaitForThreadpoolIoCallbacks) WaitForThreadpoolIoCallbacks{ nullptr };
		decltype(&WaitForThreadpoolTimerCallbacks) WaitForThreadpoolTimerCallbacks{ nullptr };
		decltype(&WaitForThreadpoolWaitCallbacks) WaitForThreadpoolWaitCallbacks{ nullptr };
		decltype(&WaitForThreadpoolWorkCallbacks) WaitForThreadpoolWorkCallbacks{ nullptr };
		decltype(&WaitNamedPipeW) WaitNamedPipeW{ nullptr };
		decltype(&WideCharToMultiByte) WideCharToMultiByte{ nullptr };
		decltype(&WinStationEnumerateProcesses) WinStationEnumerateProcesses{ nullptr };
		decltype(&WinStationSendMessageW) WinStationSendMessageW{ nullptr };
		decltype(&WinStationTerminateProcess) WinStationTerminateProcess{ nullptr };
		decltype(&WinVerifyTrust) WinVerifyTrust{ nullptr };
		decltype(&WindowFromPoint) WindowFromPoint{ nullptr };
		decltype(&WNetOpenEnumW) WNetOpenEnumW{ nullptr };
		decltype(&WNetEnumResourceW) WNetEnumResourceW{ nullptr };
		decltype(&WNetCloseEnum) WNetCloseEnum{ nullptr };
		decltype(&Wow64DisableWow64FsRedirection) Wow64DisableWow64FsRedirection{ nullptr };
		decltype(&Wow64EnableWow64FsRedirection) Wow64EnableWow64FsRedirection{ nullptr };
		decltype(&Wow64GetThreadContext) Wow64GetThreadContext{ nullptr };
		decltype(&Wow64RevertWow64FsRedirection) Wow64RevertWow64FsRedirection{ nullptr };
		decltype(&WriteFile) WriteFile{ nullptr };
		decltype(&WriteProcessMemory) WriteProcessMemory{ nullptr };
		decltype(&ZwAlpcAcceptConnectPort) NtAlpcAcceptConnectPort{ nullptr };
		decltype(&ZwAlpcConnectPort) NtAlpcConnectPort{ nullptr };
		decltype(&ZwAlpcCreatePort) NtAlpcCreatePort{ nullptr };
		decltype(&ZwAlpcDisconnectPort) NtAlpcDisconnectPort{ nullptr };
		decltype(&ZwAlpcQueryInformationMessage) NtAlpcQueryInformationMessage{ nullptr };
		decltype(&ZwAlpcSendWaitReceivePort) NtAlpcSendWaitReceivePort{ nullptr };
		decltype(&gethostbyname) gethostbyname{ nullptr };
		decltype(&gethostname) gethostname{ nullptr };
		decltype(&getnameinfo) getnameinfo{ nullptr };
		decltype(&htonl) htonl{ nullptr };
		decltype(&htons) htons{ nullptr };
		decltype(&inet_addr) inet_addr{ nullptr };
		decltype(&inet_ntoa) inet_ntoa{ nullptr };
		decltype(&inet_ntop) inet_ntop{ nullptr };
		decltype(&lstrcmpA) lstrcmpA{ nullptr };
		decltype(&lstrcmpW) lstrcmpW{ nullptr };
		decltype(&memcpy) memcpy{ nullptr };
		decltype(&memcpy_s) memcpy_s{ nullptr };
		decltype(&memmove) memmove{ nullptr };
		decltype(&ntohl) ntohl{ nullptr };
		decltype(&timeGetTime) timeGetTime{ nullptr };
		// Self-defined calls
		WinAPI::TCheckElevation CheckElevation{ nullptr };
		WinAPI::TCheckSumMappedFile CheckSumMappedFile{ nullptr };
		WinAPI::TCreateEnvironmentBlock CreateEnvironmentBlock{ nullptr };
		WinAPI::TCsrGetProcessId CsrGetProcessId{ nullptr };
		WinAPI::TDestroyEnvironmentBlock DestroyEnvironmentBlock{ nullptr };
		WinAPI::TDnsGetCacheDataTable DnsGetCacheDataTable{ nullptr };
		WinAPI::TDnsRecordListFree DnsRecordListFree{ nullptr };
		WinAPI::TEndTask EndTask{ nullptr };
		WinAPI::TFreeMibTable FreeMibTable{ nullptr };
		WinAPI::TGetIpNetTable2 GetIpNetTable2{ nullptr };
		WinAPI::TGetWindowCompositionAttribute GetWindowCompositionAttribute{ nullptr };
		WinAPI::TGUIDFromString GUIDFromStringW{ nullptr };
		WinAPI::TImageEnumerateCertificates ImageEnumerateCertificates{ nullptr };
		WinAPI::TImageGetCertificateData ImageGetCertificateData{ nullptr };
		WinAPI::TImageGetCertificateHeader ImageGetCertificateHeader{ nullptr };
		WinAPI::TLdrGetProcedureAddressForCaller LdrGetProcedureAddressForCaller{ nullptr };
		WinAPI::TLdrRegisterDllNotification LdrRegisterDllNotification{ nullptr };
		WinAPI::TLdrUnregisterDllNotification LdrUnregisterDllNotification{ nullptr };
		WinAPI::TMessageBoxTimeout MessageBoxTimeout{ nullptr };
		WinAPI::TMessageBoxTimeoutW MessageBoxTimeoutW{ nullptr };
		WinAPI::TNtCreateProcessStateChange NtCreateProcessStateChange{ nullptr };
		WinAPI::TNtChangeProcessState NtChangeProcessState{ nullptr };
		WinAPI::TNtCreateThreadEx NtCreateThreadEx{ nullptr };
		WinAPI::TNtGetNextProcess NtGetNextProcess{ nullptr };
		WinAPI::TNtGetNextThread NtGetNextThread{ nullptr };
		WinAPI::TNtGetTickCount NtGetTickCount{ nullptr };
		WinAPI::TNtQueryWnfStateData NtQueryWnfStateData{ nullptr };
		WinAPI::TNtWow64QueryInformationProcess64 NtWow64QueryInformationProcess64{ nullptr };
		WinAPI::TNtWow64ReadVirtualMemory64 NtWow64ReadVirtualMemory64{ nullptr };
		WinAPI::TNtWow64WriteVirtualMemory64 NtWow64WriteVirtualMemory64{ nullptr };
		WinAPI::TRtlAddFunctionTable RtlAddFunctionTable{ nullptr };
		WinAPI::TRtlCreateProcessParametersEx RtlCreateProcessParametersEx{ nullptr };
		WinAPI::TRtlDosApplyFileIsolationRedirection_Ustr RtlDosApplyFileIsolationRedirection_Ustr{ nullptr };
		WinAPI::TRtlGetUnloadEventTraceEx RtlGetUnloadEventTraceEx{ nullptr };
#ifdef _M_X64
		WinAPI::TRtlLookupFunctionEntry RtlLookupFunctionEntry{ nullptr };
#endif
		WinAPI::TRtlRetrieveNtUserPfn RtlRetrieveNtUserPfn{ nullptr };
		WinAPI::TSetSuspendState SetSuspendState{ nullptr };
		WinAPI::TSetWindowCompositionAttribute SetWindowCompositionAttribute{ nullptr };
		WinAPI::TSfcIsFileProtected SfcIsFileProtected{ nullptr };
		WinAPI::TW32TimeSyncNow W32TimeSyncNow{ nullptr };

		// Test (encrpyted ptrs)
//		decltype(&Beep) Beep{ nullptr };
		NoMercy::EncryptedVariable <decltype(&Beep)> Beep{ nullptr };
	};
	extern std::shared_ptr <SWinModuleTable>	g_winModules;
	extern std::shared_ptr <SWinAPITable>		g_winAPIs;

	// Smart handles
	namespace SafeObjectCleanupFnc
	{
		static bool ClnCloseHandle(const HANDLE &handle)           { return BOOLIFY(g_winAPIs->CloseHandle(handle));                  };
		static bool ClnFreeLibrary(const HMODULE &handle)          { return BOOLIFY(g_winAPIs->FreeLibrary(handle));                  };
		static bool ClnLocalFree(const HLOCAL &handle)             { return (g_winAPIs->LocalFree(handle) == nullptr);                };
		static bool ClnGlobalFree(const HGLOBAL &handle)           { return (g_winAPIs->GlobalFree(handle) == nullptr);               };
		static bool ClnUnmapViewOfFile(const PVOID &handle)        { return BOOLIFY(g_winAPIs->UnmapViewOfFile(handle));              };
		static bool ClnCloseDesktop(const HDESK &handle)           { return BOOLIFY(g_winAPIs->CloseDesktop(handle));                 };
		static bool ClnCloseWindowStation(const HWINSTA &handle)   { return BOOLIFY(g_winAPIs->CloseWindowStation(handle));           };
		static bool ClnCloseServiceHandle(const SC_HANDLE &handle) { return BOOLIFY(g_winAPIs->CloseServiceHandle(handle));           };
		static bool ClnVirtualFree(const PVOID &handle)            { return BOOLIFY(g_winAPIs->VirtualFree(handle, 0, MEM_RELEASE));  };
		static bool ClnCryptMsgClose(const HCRYPTMSG& handle)      { return BOOLIFY(g_winAPIs->CryptMsgClose(handle));                };
		static bool ClnCertCloseStore(const HCERTSTORE& handle)    { return BOOLIFY(g_winAPIs->CertCloseStore(handle, 0));			};
		static bool ClnCertFreeCertificateContext(const PCCERT_CONTEXT& handle)     { return BOOLIFY(g_winAPIs->CertFreeCertificateContext(handle)); };
		static bool ClnCertFreeCertificateChain(const PCCERT_CHAIN_CONTEXT& handle)	{ g_winAPIs->CertFreeCertificateChain(handle); return true;	  };
	}
	using SafeHandle 		= SafeObject<HANDLE, 				SafeObjectCleanupFnc::ClnCloseHandle,					nullptr>;
	using SafeLibrary 		= SafeObject<HMODULE, 				SafeObjectCleanupFnc::ClnFreeLibrary, 					nullptr>;
	using SafeLocal 		= SafeObject<HLOCAL, 				SafeObjectCleanupFnc::ClnLocalFree, 					nullptr>;
	using SafeGlobal 		= SafeObject<HGLOBAL,				SafeObjectCleanupFnc::ClnGlobalFree, 					nullptr>;
	using SafeMapView 		= SafeObject<PVOID, 				SafeObjectCleanupFnc::ClnUnmapViewOfFile, 				nullptr>;
	using SafeDesktop 		= SafeObject<HDESK, 				SafeObjectCleanupFnc::ClnCloseDesktop, 					nullptr>;
	using SafeWindowStation = SafeObject<HWINSTA, 				SafeObjectCleanupFnc::ClnCloseWindowStation, 			nullptr>;
	using SafeService 		= SafeObject<SC_HANDLE,				SafeObjectCleanupFnc::ClnCloseServiceHandle, 			nullptr>;
	using SafeVirtual 		= SafeObject<PVOID, 				SafeObjectCleanupFnc::ClnVirtualFree, 					nullptr>;
	using SafeCryptMsg 		= SafeObject<HCRYPTMSG, 			SafeObjectCleanupFnc::ClnCryptMsgClose, 				nullptr>;
	using SafeCertStore 	= SafeObject<HCERTSTORE, 			SafeObjectCleanupFnc::ClnCertCloseStore, 				nullptr>;
	using SafeCertContext 	= SafeObject<PCCERT_CONTEXT, 		SafeObjectCleanupFnc::ClnCertFreeCertificateContext, 	nullptr>;
	using SafeCertChainCtx 	= SafeObject<PCCERT_CHAIN_CONTEXT, 	SafeObjectCleanupFnc::ClnCertFreeCertificateChain, 		nullptr>;
	
	struct SDllEntry
	{
		HMODULE		 hModule{ nullptr };
		std::wstring wstModuleName;
	};
	struct SWinAPIEntry
	{
		LPVOID		lpAddress{ nullptr };
		std::wstring wstName;
	};

	inline bool GetWindowInfoSafe(HWND hWnd, LPWINDOWINFO pwndfo)
	{
		WINDOWINFO wndfo = { 0 };

		__try
		{
			if (!g_winAPIs->GetWindowInfo(hWnd, &wndfo))
				return false;
		}
		__except (EXCEPTION_EXECUTE_HANDLER)
		{
			return false;
		}

		if (pwndfo) *pwndfo = wndfo;
		return true;
	}

	class CWinAPIManager : public CSingleton <CWinAPIManager>
	{
	public:
		CWinAPIManager();
		virtual ~CWinAPIManager();

		bool	Initialize();
		bool	HasInitialized();
		void	Release();

		bool 	BindBaseAPIs();
		bool 	BindModules();
		bool 	BindAPIs();
		bool	LoadSecureModules();
		bool	HasDuplicateModule();

		bool	IsValidHandle(HANDLE hTarget);
		bool	SafeCloseHandle(HANDLE hTarget, bool bIgnoreSanity = false);
		bool	CheckModuleIntegrity(HMODULE hModule, const std::wstring& wstModuleName, bool bKnownModule, LPDWORD dpwErrorStep);
		bool	CheckModulesIntegrity(std::wstring* pszModuleName, LPDWORD dpwErrorStep);

		bool IsBadReadPtr(const void* lpTargetAddr, std::size_t cbCheckSize);
		PVOID GetRealAddress(PVOID pAddress);

		bool		InModuleRange(HMODULE hModule, DWORD_PTR dwAddress);
		PVOID		GetModuleAddressFromName(const std::wstring& wstModuleName, bool bIsCompleteCheck = true);
		std::wstring	GetModuleNameFromAddress(DWORD_PTR dwAddress, bool bFullName = true);
		bool		IsLoadedModuleBase(DWORD_PTR dwAddress);
		bool		DestroyEntrypoint(DWORD_PTR dwAddress);
		LPVOID		GetLdrModule(DWORD_PTR dwAddress);
		LPVOID		FindOwnModuleFromAddress(DWORD_PTR dwAddress);
		DWORD		ModuleCountByAddress(HMODULE hModule);
		HMODULE		GetBaseAddressFromAddress(LPVOID pvAddress);
		void		EnumerateModules(std::function<void(LDR_DATA_TABLE_ENTRY*)> cb);
		std::vector <SDllEntry> DumpModules();
		std::wstring	GetMappedNameNative(HANDLE hProcess, HMODULE hModule);

		auto NTHelper()				{ return m_spNtAPIHelper; };
		auto SyscallHelper()		{ return m_spSyscallHelper; };
		auto SecureLibraryHelper()	{ return m_spSecureLoadLibrary; };

		bool IsCheckedWinAPI(const std::wstring& wstName);
		void AddWinAPIBackup(SWinAPIEntry* api, LPBYTE backup)	{ m_mapWinApiBackups.emplace(api, backup); };
		auto& GetWinAPIBackupContainer() const					{ return m_mapWinApiBackups; };

		void RegisterModuleTextSection(HMODULE hModule, LPVOID pvBase, std::size_t cbSize);
		std::shared_ptr <STextSectionCtx> GetModuleTextSectionInfo(HMODULE hModule) const;
		bool HasModuleTextSectionInfo(HMODULE hModule) const;

		auto GetSelfModuleList() const							{ return m_vSelfModuleList; };
		bool IsModuleExistOnModuleList(HMODULE hModule) const	{ return std::find(m_vSelfModuleList.begin(), m_vSelfModuleList.end(), hModule) != m_vSelfModuleList.end(); };
		void AddModuleToModuleList(HMODULE hModule)				{ m_vSelfModuleList.emplace_back(hModule); };
		void AddModuleToSelfLoadedModuleList(HMODULE hModule)	{ m_vSelfLoadedModuleList.emplace_back(hModule); };

		FARPROC GetProcAddressSafe(LPCWSTR lpszModuleName, LPCWSTR lpszProcName);
		ULONG_PTR GetFunctionAddressPDB(const HMODULE hModule, const WCHAR* lpwszApiName);
		bool GetFunctionNameFromAddress(HANDLE hProcess, LPVOID pModuleBase, LPVOID pObject, std::wstring& wstRefFuncName);
		bool PatchModuleHook(LPCWSTR lpszModuleName, LPCWSTR lpszProcName);

	protected:
		void BindAPIs_1();
		void BindAPIs_2();
		void BindAPIs_3();
		void BindAPIs_4();
		void BindAPIs_5();
		void BindAPIs_6();
		void BindAPIs_7();
		void BindAPIs_8();
		void BindAPIs_9();
		void BindAPIs_10();
		void BindAPIs_11();

	private:
		bool									m_bHasInitialized;

		std::shared_ptr <CNtAPI>				m_spNtAPIHelper;
		std::shared_ptr <CSyscall>				m_spSyscallHelper;
		std::shared_ptr <CSecureLoadLibrary>	m_spSecureLoadLibrary;

		std::map <SWinAPIEntry*, LPBYTE>		m_mapWinApiBackups;
		std::vector	<HMODULE>					m_vSelfModuleList;
		std::vector	<HMODULE>					m_vSelfLoadedModuleList;
		std::map <std::wstring, std::wstring>		m_mapWhitelistedGameModules;
		std::map <HMODULE, std::shared_ptr <STextSectionCtx>> m_mapModuleTextSections;
	};
};
