#pragma once

namespace NoMercy
{
	enum class ECheatDBErrorCodes : uint8_t
	{
		ERROR_NONE = 0,
		DB_FILE_OPEN_FAIL = 1,
		DB_FILE_READ_FAIL = 2,
		DB_FILE_CORRUPTED = 3,
		DB_FILE_NOT_VALID = 4,
		DB_FILE_VERSION_NOT_VALID = 5,
		DB_FILE_SIZE_METADATA_NOT_VALID = 6,
		DB_FILE_HASH_METADATA_NOT_VALID = 7,
		DB_FILE_FINAL_SIZE_METADATA_NOT_VALID = 8,
		DB_FILE_FINAL_HASH_METADATA_NOT_VALID = 9,
		DB_FILE_MEMORY_BUFFER_ALLOC_FAIL = 10,
		DB_FILE_FINAL_HASH_NOT_VALID = 11,
		DB_FILE_DECRYPTION_FAIL = 12,
		DB_FILE_DECOMPRESSION_FAIL = 13,
		DB_FILE_DECOMPRESSED_HASH_NOT_VALID = 14,
	};

	enum class ECheatDBProcessingErrorCodes : uint8_t
	{
		ERROR_NONE = 0,
		DB_DATA_NULL = 1,
		DB_JSON_PARSE_FAIL = 2,
		DB_JSON_BASE_NOT_OBJECT = 3,
		DB_BLACKLIST_BASE_NOT_ARRAY = 4,
		DB_BLACKLIST_ITEM_NOT_OBJECT = 5,
		DB_BLACKLIST_ITEM_MISSING_STRUCTURE = 6,
		DB_BLACKLIST_ITEM_INVALID_STRUCTURE = 7,
		DB_BLACKLIST_ITEM_NOT_VALID_MEMBER = 8,
		DB_BLACKLIST_ITEM_INVALID_OPTION_VALUE = 9,
		DB_BLACKLIST_ITEM_INVALID_OPTION_NAME = 10,
		DB_BLACKLIST_ITEM_INVALID_PARAM_TYPE = 11,
		DB_WHITELIST_NOT_ARRAY = 12,
		DB_WHITELIST_ITEM_NOT_OBJECT = 13,
		DB_WHITELIST_ITEM_MISSING_STRUCTURE = 14,
		DB_WHITELIST_ITEM_INVALID_STRUCTURE = 15,
		DB_WHITELIST_ITEM_NOT_VALID_MEMBER = 16,
		DB_WHITELIST_ITEM_INVALID_OPTION_VALUE = 17,
		DB_WHITELIST_ITEM_INVALID_OPTION_NAME = 18,
		DB_WHITELIST_ITEM_INVALID_PARAM_TYPE = 19,
		DB_SINGLE_OBJECT_BASE_NOT_ARRAY = 20,
		DB_SINGLE_OBJECT_ITEM_NOT_OBJECT = 21,
		DB_SINGLE_OBJECT_ITEM_MISSING_MEMBER = 22,
		DB_SINGLE_OBJECT_ITEM_NOT_VALID_MEMBER = 23,
		DB_SINGLE_OBJECT_ITEM_NOT_VALID_VALUE = 24,
		DB_SINGLE_OBJECT_ITEM_NOT_VALID_PARAM_VALUE = 25,
		DB_SINGLE_OBJECT_ITEM_EMPTY_PARAM_VALUE = 26,
		DB_SINGLE_OBJECT_ITEM_PARAM_VALUE_NOT_NUMBER = 27,
		DB_SINGLE_OBJECT_ITEM_PARAM_INDEX_OVERFLOW = 28,
		DB_DATE_TYPE_NOT_VALID = 29,
		DB_UNKNOWN_NODE_NAME = 30,
	};

	enum ECheatDBScanMethods
	{
		CHEAT_DB_SCAN_NULL = 0,
		CHEAT_DB_SCAN_PROCESS_NAME = 1,
		CHEAT_DB_SCAN_PROCESS_CHECKSUM = 2,
		CHEAT_DB_SCAN_MODULE_NAME = 3,
		CHEAT_DB_SCAN_MODULE_FILE_CHECKSUM = 4,
		CHEAT_DB_SCAN_WINDOW_TITLE_CLASS = 5,
		CHEAT_DB_SCAN_WINDOW_STYLE_EXSTYLE = 6,
		CHEAT_DB_SCAN_FILE_EXIST = 7,
		CHEAT_DB_SCAN_FILE_CHECKSUM = 8,
		CHEAT_DB_SCAN_REGION_ADDR_SUM = 9,
		CHEAT_DB_SCAN_PATTERN_SEARCH = 10,
		CHEAT_DB_SCAN_MEM_DUMP_SEARCH = 11,
		CHEAT_DB_SCAN_FILE_MAPPING_EXIST = 12,
		CHEAT_DB_SCAN_MUTEX_EXIST = 13,
		CHEAT_DB_SCAN_EVENT_EXIST = 14,
		CHEAT_DB_SCAN_SEMAPHORE_EXIST = 15,
		CHEAT_DB_SCAN_JOB_OBJECT_EXIST = 16,
		CHEAT_DB_SCAN_SYMLINK_EXIST = 17,
//		CHEAT_DB_SCAN_FOREGROUND_WINDOW_INFO = 18,
//		CHEAT_DB_SCAN_GAME_ALTERATION = 19,
//		CHEAT_DB_SCAN_TIME_MANIPULATION = 20,
		CHEAT_DB_SCAN_API_MODULE_BOUND = 21,
		CHEAT_DB_SCAN_MEM_CHECKSUM = 22,
		CHEAT_DB_SCAN_MEM_EXTENDED_CHECKSUM = 23,
		CHEAT_DB_SCAN_THREAD_EBP_REGISTER = 24,
		CHEAT_DB_SCAN_YARA_FILE = 25,
		CHEAT_DB_SCAN_REGISTRY_KEY = 26,
		CHEAT_DB_SCAN_WINDOWS_STATION = 27,
		CHEAT_DB_SCAN_WAITABLE_TIMER = 28,
		CHEAT_DB_SCAN_HANDLE_OBJECT_NAME = 29,
		CHEAT_DB_SCAN_PATTERN_SEARCH_GLOBAL = 30,
		CHEAT_DB_SCAN_MAX
	};

	enum ECheatWhitelistTypes
	{
		SCAN_WHITELIST_NULL = 0,
		SCAN_WHITELIST_PROCESS_HOLLOWING = 1,
		SCAN_WHITELIST_ARBITARY_USER_POINTER_MODULE = 2,
		SCAN_WHITELIST_DEBUG_PRIV_REMOVED_PROCESS = 3,
		SCAN_WHITELIST_WINDOW_SCAN_CLASS = 4,
		SCAN_WHITELIST_MAX
	};

	enum ECheatBlacklistTypes
	{
		SCAN_BLACKLIST_NULL = 0,
		SCAN_BLACKLIST_SYMLINK = 1,
		SCAN_BLACKLIST_EVENT = 2,
		SCAN_BLACKLIST_FILEMAPPING = 3,
		SCAN_BLACKLIST_WINDOW_TITLE = 4,
		SCAN_BLACKLIST_WINDOW_CLASS = 5,
		SCAN_BLACKLIST_MODULE_NAME = 6,
		SCAN_BLACKLIST_PROCESS_NAME = 7,
		SCAN_BLACKLIST_SERVICE_NAME = 8,
		SCAN_BLACKLIST_HANDLE_OWNER_CLASS = 9,
		SCAN_BLACKLIST_DRIVER_FILENAME = 10,
		SCAN_BLACKLIST_MODULE_TIMESTAMP = 11,
		SCAN_BLACKLIST_MODULE_EXPORT_FUNC_NAME = 12,
		SCAN_BLACKLIST_OUTPUT_DEBUG_STRINGS = 13,
		SCAN_BLACKLIST_MAX
	};

	enum EBlockedToolCategories
	{
		BLOCKED_TOOL_CATEGORY_NULL = 0,
		BLOCKED_TOOL_CATEGORY_GENERIC = 1,
		BLOCKED_TOOL_CATEGORY_CERT_PROVIDER = 2,
		BLOCKED_TOOL_CATEGORY_GAME_SPECIFIC = 3,
		BLOCKED_TOOL_CATEGORY_MEM_SCANNER = 4,
		BLOCKED_TOOL_CATEGORY_MEM_VIEWER = 5,
		BLOCKED_TOOL_CATEGORY_GRAPHIC_ADDON = 6,
		BLOCKED_TOOL_CATEGORY_SYS_MONITOR = 7,
		BLOCKED_TOOL_CATEGORY_ARK = 8,
		BLOCKED_TOOL_CATEGORY_NET_MON = 9,
		BLOCKED_TOOL_CATEGORY_HWID_CHANGER = 10,
		BLOCKED_TOOL_CATEGORY_MEM_DUMPER = 11,
		BLOCKED_TOOL_CATEGORY_DEBUG_TOOL = 12,
		BLOCKED_TOOL_CATEGORY_INJECTOR = 13,
		BLOCKED_TOOL_CATEGORY_DISASSEMBLER = 14,
		BLOCKED_TOOL_CATEGORY_PE_TOOL = 15,
		BLOCKED_TOOL_CATEGORY_WINDOW_HIJACK = 16,
	};
	enum EBlockedToolActionValues
	{
		BLOCKED_TOOL_ACTION_NULL = 0,
		BLOCKED_TOOL_ACTION_WARNING = 1,
		BLOCKED_TOOL_ACTION_CLOSE_GAME = 2,
		BLOCKED_TOOL_ACTION_CLOSE_PROCESS = 3,
		BLOCKED_TOOL_ACTION_LOG = 4,
		BLOCKED_TOOL_ACTION_KICK = 5,
		BLOCKED_TOOL_ACTION_TEMP_BAN = 6,
		BLOCKED_TOOL_ACTION_PERMA_BAN = 7,
		BLOCKED_TOOL_ACTION_FORCE_MINIMIZE = 8,
		BLOCKED_TOOL_ACTION_TROLL = 9
	};

	struct SBlockedToolNode
	{
		uint32_t idx{ 0 };
		std::wstring id;
		EBlockedToolCategories category{ BLOCKED_TOOL_CATEGORY_NULL };
		std::wstring detection_name;
		EBlockedToolScanMethods method{ BLOCKED_TOOL_SCAN_BASE };
		std::wstring value;
		EBlockedToolActionValues action{ BLOCKED_TOOL_ACTION_NULL };
	};

	struct SCheatDBNode
	{
		uint32_t idx{ 0 };
		std::wstring id;
		bool from_local_db{ false };
		uint32_t type{ 0 };
		std::wstring detection_name;
		std::map <uint32_t, std::wstring> params;
	};

	struct SCheatDBWhitelist
	{
		uint32_t id{ 0 };
		uint32_t type{ 0 };
		std::vector <std::wstring> params;
	};

	struct SCheatDBBlacklistOptions
	{
		bool disabled{ false };
		bool substr{ false };
		bool case_sensitive{ false };
		bool fatal{ false };
	};
	struct SCheatDBBlacklist
	{
		uint32_t id{ 0 };
		uint32_t type{ 0 };
		std::wstring version;
		SCheatDBBlacklistOptions options;
		std::vector <std::wstring> params;
	};

	class CCheatDBManager : public std::enable_shared_from_this <CCheatDBManager>
	{
	public:
		CCheatDBManager();
		virtual ~CCheatDBManager();

		void ProcessCheatDB(const std::wstring& stData, bool bStreamed);
		bool ProcessPackedLocalCheatDB(const std::wstring& stFileName, uint8_t& pFailStep);

		void ProcessBlockedTools(const std::wstring& stData);

		auto GetDBVersion() const { return m_dwCheatDBVersion; };

	protected:
		bool __ProcessCheatDBNode(std::shared_ptr <SCheatDBNode> spNode);
		bool __ProcessWhitelistNode(std::shared_ptr <SCheatDBWhitelist> spNode);
		bool __ProcessBlacklistNode(std::shared_ptr <SCheatDBBlacklist> spNode);

		bool __ProcessBlockedToolNode(std::shared_ptr <SBlockedToolNode> spNode);

	private:
		DWORD m_dwCheatDBVersion;
		DWORD m_dwCheatDBDate;
		DWORD m_dwBlockedToolDate;
	};
};
